### ISSUE TITLE
Flip-Flop Interaction not working

### ISSUE THREAD

**Issue by sal2701** [CircuitVerse/Interactive-Book#111]
**Problem Faced**
[Flip-Flop Interaction](https://learn.circuitverse.org/docs/flipflop2.html) not working.

**Expected Behavior**
Process should start on pressing **F** which is not happening. To checkout the actual behavior, try out the older commits locally by using ```git checkout <commit id>```

**Are you working on this issue?**
Nope, For GCI 2019

**Comment by mohit-003** [comment]
I  Checked why it was not working and found that the interactive book actually uses jquery-1.11.0.min.js when I pulled it from GIT but when I checked the website it was using jquery-3.3.1.slim.min.js which does not actually handle function like .fadeIn() ,So it was not working and to make it work just change the  jquery-3.3.1.slim.min.js version with jquery-1.11.0.min.js in ../assets/js/vendor/ .It should do the job I think.
![aaa](https://user-images.githubusercontent.com/58560983/70723917-b371e900-1d1f-11ea-8da6-0db8bb7e2951.png)
![aaa1](https://user-images.githubusercontent.com/58560983/70723919-b40a7f80-1d1f-11ea-989d-db6f28aa18df.png)
![aaa2](https://user-images.githubusercontent.com/58560983/70723920-b40a7f80-1d1f-11ea-9c71-ac079856520b.png)
![aaa3](https://user-images.githubusercontent.com/58560983/70723922-b4a31600-1d1f-11ea-9f98-947dc807bd02.png)

**Comment by mohit-003** [comment]
@sal2701 Can I take issue #95 on GCI now? Will issue #111 also come as a GCI task??

**Comment by sal2701** [comment]
@mohit-003 Cool! That's right. I will shortly add a task you can claim it then. Just give me some time :smile:

**Comment by mohit-003** [comment]
Ok😁👍

**Comment by satu0king** [comment]
It is a GCI task now :)

**Comment by mohit-003** [comment]
Done!
