### ISSUE TITLE
ALU interactive Circuit

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/Interactive-Book#114]
https://learn.circuitverse.org/docs/alu.html

In addition to the below image, embed an interactive circuit of the same. 

![image](https://user-images.githubusercontent.com/2092958/70728728-f0da7480-1d27-11ea-9d5e-2ce43facc931.png)

**Comment by JoshHeng** [comment]
So I'm just creating this circuit on CircuitVerse and embedding it on the book?
