### ISSUE TITLE
Asynchronous Ripple Counter Interactive Circuit

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/Interactive-Book#115]
https://learn.circuitverse.org/docs/counter.html

Implement an interactive version of the below circuit. 

![image](https://user-images.githubusercontent.com/2092958/70729186-b6250c00-1d28-11ea-8745-f4a2b41e9ece.png)

**Comment by GrayR00t** [comment]
Is anybody is working on this ?
If not I would like to work
