### ISSUE TITLE
Synchronous Ripple Counter Interactive Circuit

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/Interactive-Book#116]
https://learn.circuitverse.org/docs/counter.html

Implement an interactive version of the circuit below. 

![image](https://user-images.githubusercontent.com/2092958/70729305-f84e4d80-1d28-11ea-86b2-14925621ded3.png)

**Comment by mohit-003** [comment]
What does this actually mean?

**Comment by satu0king** [comment]
Hey!
Go through the description of the Synchronous Ripple Counter, try and understand how it works. Then replicate the above diagram as circuit - create it on circuitverse.org/simulator. Then embed the circuit under the image. The idea is to allow users to interact with the circuit so they can understand it better.

**Comment by mohit-003** [comment]
Ok

**Comment by AymanNasser** [comment]
Hey Guys,
I'll work on synchronous counter & add some modifications to ripple counter

**Comment by pavanjoshi914** [comment]
pr for this features is merged and issue can be closed
