### ISSUE TITLE
Dark Mode toggle resets when page refreshed or topic changed

### ISSUE THREAD

**Issue by sal2701** [CircuitVerse/Interactive-Book#12]
**Describe the bug**
Whenever we change topic/refresh the dark mode toggles back to default, ie. Day mode

**To Reproduce**
Click Dark mode and refresh page

**Expected behavior**
Mode should stay as it is during a session even after changing topic or refreshing page

**Suggested Solution**
Saving the mode in local storage and make use of it while loading page.

**Are you working on this issue? (Yes/No)**
Yes

**Comment by aayush-05** [comment]
@tachyons this can be closed now.
