### ISSUE TITLE
Options in the Select tag are not visible in DarkMode.

### ISSUE THREAD

**Issue by mohit-003** [CircuitVerse/Interactive-Book#133]
![darkpreviewbefore](https://user-images.githubusercontent.com/58560983/70862580-2f5c7300-1f64-11ea-9fd6-e660c951eeff.png)

**Problem Faced**
The light colour of text in dark mode makes it difficult to read the text

**Expected Behavior**
The text should be a **darker** color

**Are you working on this issue?**
Yes

**Comment by mohit-003** [comment]
@satu0king @tachyons @ankitkataria I have made the changes can I make a PR for this?

**Comment by ShreyaPrasad1209** [comment]
@mohit-003 sure

**Comment by mohit-003** [comment]
Already done 👍😁
