### ISSUE TITLE
Bullet point size increases randomly

### ISSUE THREAD

**Issue by sal2701** [CircuitVerse/Interactive-Book#135]
**Bug Report**
The bullet point size increases randomly.

**Steps To Reproduce**
* Go to [Interactive FSM](https://learn.circuitverse.org/docs/fsm_interactive.html) page of Interactive-Book.
* Open and close the side-bar.

**Are you working on this issue?**
Nope.

**Comment by ShreyaPrasad1209** [comment]
Are you talking about the bullet points in the sidebar? They seem fine to me.

**Comment by Ananthavijay** [comment]
@ShreyaPrasad1209 I noticed that the bullet point of home vanishes in interactive fsm

**Comment by ShreyaPrasad1209** [comment]
You mean after clicking sidebar button?

**Comment by Ananthavijay** [comment]
@ShreyaPrasad1209  My bad. It's before clicking the sidebar

**Comment by aayush-05** [comment]
Actuallly it seems that the bullet point in front of Home in the sidebar disappears on the FSM page, on other pages it is visible. @ShreyaPrasad1209 
Can we have this as a GCI task @tachyons ?

**Comment by sal2701** [comment]
Sorry for the confusion, please give the screenshots a look

### In Google Chrome
![Screenshot (5)](https://user-images.githubusercontent.com/42511766/72208131-55265a80-34c5-11ea-8d51-572b553b81ba.png)

### In Mozilla Firefox
#### Happens after clicking the sidebar button twice
![Screenshot (6)](https://user-images.githubusercontent.com/42511766/72208134-61121c80-34c5-11ea-8fb4-cb22aabcfcd3.png)

**Comment by aayush-05** [comment]
In my case, the bullet point just disappears.
![image](https://user-images.githubusercontent.com/47032027/72208722-42fbea80-34cc-11ea-8ff2-b48b0e3f0b7c.png)

**Comment by Ananthavijay** [comment]
@aayush-05 You must be using Google chrome. See the screenshot sent by @sal2701. It includes both Google Chrome and Firefox

**Comment by aayush-05** [comment]
Oh, yeah !
Sorry, I overlooked the Google Chrome screenshot.

**Comment by SamriddhiMishra** [comment]
@sal2701 Can you please tell the version of the Mozilla Firefox you are using?
