### ISSUE TITLE
Inconsistent Font and Button Text

### ISSUE THREAD

**Issue by nrs1729** [CircuitVerse/Interactive-Book#150]
## What is the issue

The text in the bottom right corner is different e.g. "CircuitVerse on Github" here 
https://learn.circuitverse.org/docs/kmapi.html 
![image](https://user-images.githubusercontent.com/51863168/71359524-95f51880-2584-11ea-871c-0c6fb9f00ed7.png) 
and "Edit on Github" here 
https://learn.circuitverse.org/docs/bool.html
![image](https://user-images.githubusercontent.com/51863168/71359556-af966000-2584-11ea-949e-370cebe97ba2.png)

The fonts change from from https://learn.circuitverse.org/docs/bool.html
![image](https://user-images.githubusercontent.com/51863168/71359596-e3718580-2584-11ea-85b1-592743febf45.png)

to https://learn.circuitverse.org/docs/bool2.html
![image](https://user-images.githubusercontent.com/51863168/71359587-d81e5a00-2584-11ea-9002-af8cfccf65e3.png)

## How to resolve
Change so they are consistent over different pages - not sure which fonts and button text it should be changed to though.

**Comment by ShreyaPrasad1209** [comment]
They look consistent to me @nrs1729. What do you think @satu0king @tachyons @ankitkataria ?

**Comment by tachyons** [comment]
@nitin10s

**Comment by nitin10s** [comment]
They are inconsistent indeed, the button text should be: Edit this page
The new UX used Open Sans, but the current Interactive Book uses Helvetica. 
I'll say, use Helvetica for now, we'll change the typeface later after the completion of new UX accordingly

**Comment by nitin10s** [comment]
@ShreyaPrasad1209 This would be a good task for GCI. Please add. I could co-mentor.

**Comment by Shivansh2407** [comment]
Can I work on this @nrs1729 , @ShreyaPrasad1209

**Comment by manjotsidhu** [comment]
Fixed by #460
