### ISSUE TITLE
Improve Sidebar Button

### ISSUE THREAD

**Issue by nrs1729** [CircuitVerse/Interactive-Book#151]
Currently the button moves when the sidebar collapses/opens, and for subsections it overlaps with the text. 
![image](https://user-images.githubusercontent.com/51863168/71360130-b0c88c80-2586-11ea-9fd8-d111f01d54dd.png)

## Solution:
Change the button to something link this 
![image](https://user-images.githubusercontent.com/51863168/71360151-c8077a00-2586-11ea-9580-8ece16be733a.png)
![image](https://user-images.githubusercontent.com/51863168/71360182-d190e200-2586-11ea-8c36-0733f43a5f50.png)

## Are you working on this?
Yes

**Comment by jainpawan21** [comment]
This issue is only with subcategory of https://learn.circuitverse.org/docs/combinational

**Comment by Shivansh2407** [comment]
Can I work on this issue ?

**Comment by YashKumarVerma** [comment]
![image](https://user-images.githubusercontent.com/14032427/82024370-52bf5180-96ad-11ea-9bdd-9464ea501a84.png)

I think this issue is fixed.
What do you think @Shivansh2407

**Comment by Shivansh2407** [comment]
Yes @YashKumarVerma it is fixed .
