### ISSUE TITLE
Implement a pop quiz section after the content of each page

### ISSUE THREAD

**Issue by JoshHeng** [CircuitVerse/Interactive-Book#168]
A small, javascript pop quiz could be added at the end of each page to reinforce the content covered.
This would probably be around ten (or less) multi choice or true/false questions, which would reveal the answer immediately when they are answered. The answer would not be saved.

A system should be made where any developer can define questions and answers in a simple format (e.g. in markdown), which is then parsed.

An example of this can be seen here:
<img width="589" alt="Screenshot 2020-01-01 at 17 48 06" src="https://user-images.githubusercontent.com/34946235/71644348-df4d1280-2cbe-11ea-9431-821fc38f8a3c.png">

**Comment by Parikshit-Hooda** [comment]
An alternative implementation of this could be :
- Provide a button to open the quiz.

This approach will consider if the user actually wants to take the quiz or not.
@JoshHeng what do you think?

**Comment by JoshHeng** [comment]
> An alternative implementation of this could be :
> 
> * Provide a button to open the quiz.
> 
> This approach will consider if the user actually wants to take the quiz or not.
> @JoshHeng what do you think?

I don’t think a button is needed as it is at the end of the page anyway and is not needed to be taken if the user doesn’t want to

**Comment by JoshHeng** [comment]
And if you see the way I implemented it, it is easier for users to take it if it’s on the same page anyway (instead of having to open a new page for each quiz)
