### ISSUE TITLE
Create Issue and PR Templates

### ISSUE THREAD

**Issue by nrs1729** [CircuitVerse/Interactive-Book#169]
### Are you working on this? 
Yes

**Comment by ShreyaPrasad1209** [comment]
@nrs1729 if you want to create an issue you can do it like you created this one. If you had something else in mind then can you elaborate?

**Comment by nrs1729** [comment]
The other repositories have templates for what you're supposed to put in the issues as guidelines (like this https://github.com/CircuitVerse/CircuitVerse/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) that come up when you create an issue/PR, I meant adding them for this repo as well.

**Comment by aayush-05** [comment]
PRs have been already made to fix this, they will be merged shortly. 
You can close this issue @nrs1729

**Comment by nrs1729** [comment]
Okay cool
