### ISSUE TITLE
Error in installation and running.

### ISSUE THREAD

**Issue by netkeojas** [CircuitVerse/Interactive-Book#17]
$ bundle install
_Traceback (most recent call last):
	2: from /home/ojas/.rbenv/versions/2.5.1/bin/bundle:23:in `<main>'
	1: from /home/ojas/.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/home/ojas/.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)_

**Comment by ankitkataria** [comment]
Hey @netkeojas , you'll have to install ruby and bundler(`gem install bundler`) before doing a `bundle install`.
