### ISSUE TITLE
Remove Disqus from website

### ISSUE THREAD

**Issue by JoshHeng** [CircuitVerse/Interactive-Book#171]
I don't see the point of having Disqus on an educational, static website.

Why would users need to comment or offer their thoughts? If they needed help, they would be better joining us on Slack or Discord where we are all active, instead of leaving a comment that everyone could see.

Having comments enabled could also discourage educational institutions from using our website, for example. This makes it possible for innapropiate language to be seen on the page, even if there is some sort of moderation.

Disqus is more suited to a blog website, or for reviewing other people's circuits. But I don't believe that this is a suitable place for it

**Comment by jainpawan21** [comment]
@JoshHeng Having disqus on every page gives freedom to every user to give their feedback about content of the that page. If they want to add something they can add.
If we take offensive and inappropriate comments, site moderators can delete those comments.

**Comment by ShreyaPrasad1209** [comment]
@JoshHeng can you please close this issue?

**Comment by JoshHeng** [comment]
Issue closed, will keep commenting feature
