### ISSUE TITLE
Starred/Number of Views tab unresponsive

### ISSUE THREAD

**Issue by ShreyaPrasad1209** [CircuitVerse/Interactive-Book#19]
**Problem**
Starred/Number of Views tab unresponsive as shown in screenshot.

**Changes proposed**
Use media query for maintaining the width of the tab. Verify by inspection

**Screenshot** 
![image](https://user-images.githubusercontent.com/43600306/68069140-30ee2500-fd82-11e9-816a-3d0726b58daf.png)

**Comment by aayush-05** [comment]
@tachyons @nitin10s this can be closed, issue resolved under new UI
