### ISSUE TITLE
Bucketlist

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/Interactive-Book#2]
These are minor things that can help in the long run. 
- [ ] Edit on Github link 
- [ ] References page
- [ ] Google Analytics Tracking

**Comment by aayush-05** [comment]
@satu0king is the Google Analytics part done ? If yes, then we can close this issue

**Comment by ShubhankarKG** [comment]
All three things are done. I think we can close this issue @YashKumarVerma .

**Comment by YashKumarVerma** [comment]
thanks, @ShubhankarKG @aayush-05 for notifying.
