### ISSUE TITLE
Display shadow effect on hover

### ISSUE THREAD

**Issue by ShreyaPrasad1209** [CircuitVerse/Interactive-Book#20]
Apply shadow effect on boxes containing digital circuits when hovered by mouse.

![2019-11-02 (1)](https://user-images.githubusercontent.com/43600306/68069243-a3abd000-fd83-11e9-8d6c-e3a58a88c55c.png)

**Comment by SamriddhiMishra** [comment]
Can I work on this?

**Comment by ShreyaPrasad1209** [comment]
Sure

**Comment by aayush-05** [comment]
@tachyons @nitin10s this can be closed, platform has been revamped
