### ISSUE TITLE
The Interactive Karnaugh Map uses k-map layout it can have a default layout.

### ISSUE THREAD

**Issue by mohit-003** [CircuitVerse/Interactive-Book#223]
By setting the Interactive Karnaugh Map page to default layout it will fix some issues like, the page doesn't have a button to toggle the side-bar.
![image](https://user-images.githubusercontent.com/58560983/73123531-16a99900-3fb7-11ea-9b1f-917dfae8b753.png)

**Comment by ShubhankarKG** [comment]
This issue is resolved in #297 . @YashKumarVerma this can be closed.

**Comment by YashKumarVerma** [comment]
> This issue is resolved in #297 . @YashKumarVerma this can be closed.

**Comment by YashKumarVerma** [comment]
Thanks, @ShubhankarKG @mohit-003
