### ISSUE TITLE
Flip-flop Interaction (Discussion)

### ISSUE THREAD

**Issue by Ananthavijay** [CircuitVerse/Interactive-Book#225]
While doing the _Elaborate Flip-flop Interaction_ and _Fix Flip-flop state table_ tasks I did a lot of research about flip-flops and came to know that there is only one set of input, output equations which are correct.
#### Currently
The flip-flop interaction lets the user enter the input and output equations, with which a state table is generated. If the equations are wrong it results undefined. If the state table is generated without any errors there is no way to check whether the user's input, output equations are correct. This results in the generation of a state table that may be wrong.

#### My Proposal
We should restrict the user to enter input, output equations. The state table should be generated with only the flip-flop type and count entered by the user.

**Comment by GrayR00t** [comment]
I would like to work this issue

**Comment by Ananthavijay** [comment]
@GrayR00t Let everyone give their views on this one

**Comment by Ananthavijay** [comment]
This issue will be followed in this [PR](https://github.com/CircuitVerse/Interactive-Book/pull/181) so closing this
