### ISSUE TITLE
Change font color in dark mode

### ISSUE THREAD

**Issue by deepak2431** [CircuitVerse/Interactive-Book#23]
#### I am submitting a -
* [] **Bug Report**

#### Describe your bug/feature - 
The color of the button text is not visible in dark mode.

#### Screenshots (if relevant) -

![Screenshot from 2019-11-05 20-39-43](https://user-images.githubusercontent.com/44617923/68220097-1b406000-000d-11ea-95d9-ace723202cb2.png)

**Comment by satu0king** [comment]
Similar/duplicate of #52

**Comment by deepak2431** [comment]
@satu0king Will close this.
