### ISSUE TITLE
Issue with Sidebar button in some pages

### ISSUE THREAD

**Issue by Ananthavijay** [CircuitVerse/Interactive-Book#236]
- [x] [Interactive Karnaugh Map](https://learn.circuitverse.org/docs/kmapi.html) - Doesn't have a sidebar button. 
- [ ] [Half Adder](https://learn.circuitverse.org/docs/Combinational/half_adder.html) - Doesn't have the icon in sidebar button.

**Comment by yash15601** [comment]
@Ananthavijay can i work on this??

**Comment by Ananthavijay** [comment]
Sure @yash15601

**Comment by abhinavsri360** [comment]
I am working on this.

**Comment by abhinavsri360** [comment]
I have fixed this in the above Pull Request.
