### ISSUE TITLE
Add XNOR gate tutorial

### ISSUE THREAD

**Issue by deepak2431** [CircuitVerse/Interactive-Book#24]
#### I am submitting a -
* [] **Feature Request**

#### Describe your bug/feature -
 In the logic gates tutorial the tutorial for the XNOR gate is missing. Add the tutorial of XNOR gate to the section of logic gates.

**Comment by coding-CEO** [comment]
@YashKumarVerma I think this issue can be closed.
Because, there is no such issue in the current repo as described here.
