### ISSUE TITLE
TextContent on Dark Mode button remains unchanged after switching to dark theme

### ISSUE THREAD

**Issue by Batey96** [CircuitVerse/Interactive-Book#240]
Current Problem:
the text on the Dark Mode button doesnot change after toggling the page into dark theme.
This is a poor UI experience for users as shown below
![Screenshot from 2020-02-29 13-46-15](https://user-images.githubusercontent.com/24868289/75607689-13478700-5afa-11ea-9641-b22b031df68d.png)
Proposed Solution:
the Text on the Dark Mode button should change after toggling the page into dark theme.The solution is to ask the user to switch to dark mode when the page is on normal/light mode and vice versa as shown below
![Interactive Gates - CircuitVerse](https://user-images.githubusercontent.com/24868289/75612164-56692080-5b21-11ea-95f3-d8293e17f9a7.gif)

**Comment by Batey96** [comment]
my PR is ready to be submitted.Just waiting for @stakeholders to consider this as a valid issue

**Comment by Shivansh2407** [comment]
Fixed in #245
