### ISSUE TITLE
alignment issue issue with the Operator in Binary part 

### ISSUE THREAD

**Issue by mahmodHammad** [CircuitVerse/Interactive-Book#242]
At /docs/binary2.html  the operator section looks like this : 
![image](https://user-images.githubusercontent.com/41790090/76133738-4fab4380-6022-11ea-98dd-ff69ee647342.png)

are you working on it ? 
- YES

**Comment by mahmodHammad** [comment]
https://github.com/CircuitVerse/Interactive-Book/pull/243

**Comment by coding-CEO** [comment]
I fixed this issue in #262

**Comment by coding-CEO** [comment]
The solution of issue is not there. I think the merge got revert somehow. I created another PR #279  to solve this issue.
