### ISSUE TITLE
Dark mode anchor tag does not update on css transitions.

### ISSUE THREAD

**Issue by ShubhankarKG** [CircuitVerse/Interactive-Book#244]
![Screenshot from 2020-03-14 09-08-08](https://user-images.githubusercontent.com/50791000/76674284-988b6b00-65d3-11ea-9f26-639f82c2c764.png)
![Screenshot from 2020-03-14 09-08-05](https://user-images.githubusercontent.com/50791000/76674285-9cb78880-65d3-11ea-9731-3d2578254d2c.png)

**Comment by aayush-05** [comment]
Duplicate issue, already opened at #240

**Comment by ShubhankarKG** [comment]
Closing this since the PR is already merged.
