### ISSUE TITLE
Search text is not visible in Dark Mode

### ISSUE THREAD

**Issue by pranavmodx** [CircuitVerse/Interactive-Book#246]
![Screenshot 2020-03-16 at 1 03 56 AM](https://user-images.githubusercontent.com/42793024/76709131-207f8b00-6722-11ea-838c-e02b0c571ac2.png)
![Screenshot 2020-03-16 at 1 04 15 AM](https://user-images.githubusercontent.com/42793024/76709132-21b0b800-6722-11ea-9eb7-f76ca182eea0.png)

Solution : Add conditionals and change text color according to mode selected.

I am working on this issue.

**Comment by kakubotics** [comment]
Is it working now? @pranavmodx

**Comment by pranavmodx** [comment]
Yes, I've made a PR which will solve this issue.

**Comment by coding-CEO** [comment]
I solved this problem without changing the background color of search bar in #320 .
