### ISSUE TITLE
Redundant hyperlinks

### ISSUE THREAD

**Issue by ShubhankarKG** [CircuitVerse/Interactive-Book#248]
![Screenshot from 2020-03-16 08-08-21](https://user-images.githubusercontent.com/50791000/76719570-285e2000-6760-11ea-878d-20c68f513e8c.png)

The top left CircuitVerse icon redirects to same page instead of going to CircuitVerse's official page.

**Comment by kakubotics** [comment]
Let me give a chance to make it work @ShubhankarKG

**Comment by ShubhankarKG** [comment]
Well the PR was already submitted back then. Pull #249 does the same task.

**Comment by kakubotics** [comment]
Well it was still open so i did

**Comment by ShubhankarKG** [comment]
Could have had a look at least before opening a PR.
