### ISSUE TITLE
Fix text overriding

### ISSUE THREAD

**Issue by deepak2431** [CircuitVerse/Interactive-Book#25]
#### I am submitting a -
* [] **Bug Report**

#### Describe your bug/feature -
The digit 0 appears to override the box.

#### Screenshots (if relevant) -
![Screenshot from 2019-11-05 21-48-48](https://user-images.githubusercontent.com/44617923/68225411-627f1e80-0016-11ea-9fe9-f67bfb3a4ee1.png)

**Comment by sakshi1499** [comment]
@deepak2431 Overriding is not visible in my interactive book. Can you check again? If it exists can you confirm that the PR raised by @fluctix is solving the problem?
