### ISSUE TITLE
Still old logo in Interactive Book

### ISSUE THREAD

**Issue by nitin10s** [CircuitVerse/Interactive-Book#253]
The interactive book still has the old logo as favicon

**Comment by Nitish145** [comment]
Can i work on it ?

**Comment by nitin10s** [comment]
Sure

**Comment by ShubhankarKG** [comment]
Are you working on it @Nitish145 ?

**Comment by Nitish145** [comment]
Already fired a PR for the same..

**Comment by ShubhankarKG** [comment]
Cool, I didn't notice a link here. Good work !

**Comment by YashKumarVerma** [comment]
Good work @Nitish145
