### ISSUE TITLE
Sticky Navigation bar not disappear on Learn and Documentation page.

### ISSUE THREAD

**Issue by surajsly** [CircuitVerse/Interactive-Book#266]
The sticky Navigation bar does not disappear on Learn and Documentation page. Which Make it difficult to navigate through these pages and go to other pages. which will result in time waste and **bad User experience** on the Website.

>at Learn page 
[https://learn.circuitverse.org/](https://learn.circuitverse.org/)  

>at Documentation Page
[https://docs.circuitverse.org/#/](https://docs.circuitverse.org/#/)

**I would like to modify these changes if a chance is given to me**

**Comment by aayush-05** [comment]
Would you please explain it a little bit, I am unable to get the bug ?

**Comment by surajsly** [comment]
yes the main problem is you can not go back to main website one you click on the LEARN tab on main website, there is no way to go back to the main website.

**Comment by YashKumarVerma** [comment]
Hello there @surajsly 
I was trying to reproduce the bug but was unable to do so, could you please help? What exactly is the error you want to mention? 
Maybe adding an image showing the expected or actual version might help

![image](https://user-images.githubusercontent.com/14032427/82003081-1542d000-967d-11ea-8df5-158cefeb9ecb.png)

from the part which I could understand:
- I was able to easily navigate through the sidebar.

**Comment by coding-CEO** [comment]
I think @surajsly is trying to say that,
from https://learn.circuitverse.org/ you can go to https://circuitverse.org/
but,
from https://docs.circuitverse.org/#/ you Can Not go to https://circuitverse.org/

**Comment by YashKumarVerma** [comment]
> I think @surajsly is trying to say that,
> from https://learn.circuitverse.org/ you **Can** go to https://circuitverse.org/
> but,
> from https://docs.circuitverse.org/#/ you **Can Not** go to https://circuitverse.org/
> 
> If anyone Wants, I can start working on this issue immediately.

the title says "Sticky Navigation bar not disappear on Learn and Documentation page." 

Either the title is inappropriate or the body.
However, since @coding-CEO 's suggestion is apt, can you please open an issue in the respective repository?

**Comment by abhinavsri360** [comment]
I don't think this is an issue we can always go back to https://circuitverse.org/ from https://docs.circuitverse.org/#/  by toggling on CircuitVerse present on the top-left corner. All we can do to make this notice is that make the heading on top-left more visible by either changing its color or simply making it bold. I think this resolves the issue.

**Comment by YashKumarVerma** [comment]
> I don't think this is an issue we can always go back to https://circuitverse.org/ from https://docs.circuitverse.org/#/ by toggling on CircuitVerse present on the top-left corner. All we can do to make this notice is that make the heading on top-left more visible by either changing its color or simply making it bold. I think this resolves the issue.

![image](https://user-images.githubusercontent.com/14032427/82045574-f2d8a300-96cc-11ea-8791-a32f736d88bc.png)
the circuit verse documentation heading takes user to docs.circuitverse.org not circuitverse.org

**Comment by abhinavsri360** [comment]
I thought the issue was related to the interactive-book repository. I think this issue is present ina the wrong repository. I am opening an issue in the Docs repository for the same.

**Comment by coding-CEO** [comment]
@YashKumarVerma @Shivansh2407 I think this issue can be closed.
