### ISSUE TITLE
Unwanted files across repository

### ISSUE THREAD

**Issue by YashKumarVerma** [CircuitVerse/Interactive-Book#273]
There are some `.DS_STORE` files in many directories, which need to be removed. 

- [ ] https://github.com/CircuitVerse/Interactive-Book/blob/master/_includes/.DS_Store
- [ ] https://github.com/CircuitVerse/Interactive-Book/blob/master/assets/.DS_Store
- [ ] https://github.com/CircuitVerse/Interactive-Book/blob/master/assets/images/.DS_Store
- [ ] https://github.com/CircuitVerse/Interactive-Book/blob/master/docs/.DS_Store

also, the `gitignore` needs to be updated accordingly.

**Comment by ShubhankarKG** [comment]
I'd like to take this one up.

**Comment by YashKumarVerma** [comment]
sure @ShubhankarKG

**Comment by ShubhankarKG** [comment]
It seems to me that the VSCode or any other preferred IDE has an internal configuration of not showing certain files, for example __.git__ and __.DS_Store__. That could have been a reason why the files were present but were not excluded as such.
