### ISSUE TITLE
Fix typo of button text

### ISSUE THREAD

**Issue by deepak2431** [CircuitVerse/Interactive-Book#29]
#### I am submitting a -
* [] **Bug Report**

#### Describe your bug/feature - 
The initial of button text No is in small letter.

#### Screenshots (if relevant) - 
![Screenshot from 2019-11-06 01-22-38](https://user-images.githubusercontent.com/44617923/68241422-a3862b80-0034-11ea-9ff8-c9c2de552c0d.png)

**Comment by deepak2431** [comment]
@Parikshit-Hooda  I think this issue can be added as the similar task you have been looking as beginner level task for GCI which would help the students to understand how to raise their first pull request.

**Comment by satu0king** [comment]
@deepak2431 could you clarify which button text are you referring to ?

**Comment by deepak2431** [comment]
@satu0king I am referring to the button text of Allow don't care and Hide result.

**Comment by satu0king** [comment]
To clarify, the fix is changing "no" to "No" in the drop down.

**Comment by aayush-05** [comment]
@tachyons @nitin10s this can be closed, invalid issue (https://github.com/CircuitVerse/Interactive-Book/pull/125#issuecomment-569616060)
