### ISSUE TITLE
List items in BooleanAlgebra.md

### ISSUE THREAD

**Issue by abhinavsri360** [CircuitVerse/Interactive-Book#290]
## Is your feature request related to a problem? Please describe.

No
The simulator present in the end which consists of the words 'AND', 'OR', 'XOR', and 'NOT' might not be a good option for presentation.
## Describe the solution you'd like

I propose to have a gate image along with its name present inside the gate image(can use SVG image for that) instead of gate name.

## Describe alternatives you've considered

Just have gate representation with the name of the gate in the center of that image. As the names present are quite big and look creepy.

## Additional context

I think the context above describes my problem well.

**Comment by coding-CEO** [comment]
I am currently working on this issue. I will solve this very soon.

**Comment by coding-CEO** [comment]
I fixed this issue in #307 
Review @YashKumarVerma @abhinavsri360
