### ISSUE TITLE
Too much extra space in the examples of Commutative and associative law 

### ISSUE THREAD

**Issue by YashKumarVerma** [CircuitVerse/Interactive-Book#294]
There is too much extra space in the examples of Commutative and associative law which make one of the two examples kinda invisible in the mobile view. A solution could be that examples can be presented in different lines.
Please look into this.
@YashKumarVerma @Dishebh

_Originally posted by @abhinavsri360 in https://github.com/CircuitVerse/Interactive-Book/pull/288#issuecomment-629602633_

**Comment by coding-CEO** [comment]
Can I work on this ???

**Comment by coding-CEO** [comment]
I fixed this issue in #296.
@YashKumarVerma  Please review.
