### ISSUE TITLE
One flip flop missing

### ISSUE THREAD

**Issue by dev9414** [CircuitVerse/Interactive-Book#30]
In flip flop section there is only 
1)SR
2)JK
3)D
4)T
FLIP FLOP are available
But MASTER-SLAVE flip flop is missing

**Comment by ericsheng495** [comment]
https://docs.google.com/document/d/1YEHii5TEDmni2g8H2LBDrISY0iYtgBDmIIawK0n-f-c/edit?usp=sharing

**Comment by Ananthavijay** [comment]
@ericsheng495 Please add this in the interactive-Book.
