### ISSUE TITLE
Table of Contents

### ISSUE THREAD

**Issue by abhinavsri360** [CircuitVerse/Interactive-Book#303]
## Describe the bug
Table of Contents not visible in the Boolean Algebra Page.
~~A clear and concise description of what the bug is.~~

## To Reproduce

~~Steps to reproduce the behavior:~~

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

## ~~Expected behavior~~

~~A clear and concise description of what you expected to happen.~~

## ~~Desktop (please complete the following information):~~

* ~~OS: [e.g. iOS]~~
* ~~Browser [e.g. chrome, safari]~~
* ~~Version [e.g. 22]~~

## ~~Smartphone (please complete the following information):~~

* ~~Device: [e.g. iPhone6]~~
* ~~OS: [e.g. iOS8.1]~~
* ~~Browser [e.g. stock browser, safari]~~
* ~~Version [e.g. 22]~~

**Comment by abhinavsri360** [comment]
![image](https://user-images.githubusercontent.com/44001310/82158580-6da8e600-98a6-11ea-96de-2ad07b6d1466.png)

**Comment by abhinavsri360** [comment]
I have fixed this in the PR #304

**Comment by coding-CEO** [comment]
@YashKumarVerma please close this issue.

**Comment by abhinavsri360** [comment]
Closes via #304
