### ISSUE TITLE
Typo in references page

### ISSUE THREAD

**Issue by ShubhankarKG** [CircuitVerse/Interactive-Book#305]
## Describe the bug

The reference page has a link named https://electronicsforu.com/resources/learn-electronics/flip-flop-rs-jk-t-dputting which is a typo error. This leads to a 404 on going to the site specified.

## To Reproduce

1.  Go to 'https://learn.circuitverse.org'
2.  Click on 'references'
3.  Scroll down to 'point 4'
4.  Click the link to see error.

## Expected behavior

A new page that opens up a specified reference resource.

## Screenshots

![Screenshot from 2020-05-18 09-30-53](https://user-images.githubusercontent.com/50791000/82173352-876c1c80-98ea-11ea-9aa1-91e1272caed6.png)
![Screenshot from 2020-05-18 09-31-06](https://user-images.githubusercontent.com/50791000/82173354-8a670d00-98ea-11ea-99a9-ed37159e34e3.png)

## Desktop (please complete the following information):

* OS: Ubuntu 18.04
* Browser: Chrome
* Version [e.g. 22]

## Additional context

Two other things to note:

1. The __Reference.md__ begins with a capital R. This is inconsistent with all files. Need to rename that.
2. The **target: _blank** without the use of __rel="noopener noreferrer"__ is considered bad practice with respect to performance and security issues.  Need to add that as well.

**Comment by Shivansh2407** [comment]
Are you working with this issue @ShubhankarKG ?

**Comment by ShubhankarKG** [comment]
Yes. Will send a PR soon

**Comment by Shivansh2407** [comment]
Sure. The correct Link is : https://www.electronicsforu.com/resources/learn-electronics/flip-flop-rs-jk-t-d
