### ISSUE TITLE
Text not visible in Dark mode

### ISSUE THREAD

**Issue by coding-CEO** [CircuitVerse/Interactive-Book#308]
Make the text visible in the dark mode.

![b](https://user-images.githubusercontent.com/52625909/82182516-0751b100-9902-11ea-906f-14a31138a536.jpg)
![a](https://user-images.githubusercontent.com/52625909/82182521-091b7480-9902-11ea-9157-637cf5b439f4.jpg)

### Are you Working on this Issue ??
**NO. Anyone can take and solve this issue.**

**Comment by nileshdas** [comment]
Can I work on this issue? @YashKumarVerma

**Comment by YashKumarVerma** [comment]
Yes
