### ISSUE TITLE
Simulator invisible in mobile view

### ISSUE THREAD

**Issue by abhinavsri360** [CircuitVerse/Interactive-Book#310]
## Describe the bug
The simulator present on the Boolean Algebra page is invisible for the mobile view.

## To Reproduce
reproduced in #390 

## Expected behavior
Should be visible on mobile view as well

## Screenshots
![Screenshot_20200518-132052](https://user-images.githubusercontent.com/44001310/82187868-aaa6c400-990a-11ea-940b-625bcbf986f6.png)

I am working on this issue.

**Comment by Shivansh2407** [comment]
Please Mention the Link by writing out the steps to reproduce. Mention Where you are Working on this? Also Please Add a Screenshot if Possible.

**Comment by abhinavsri360** [comment]
Sure I'll take care of these measures by next time.
As of now I am I am not working on this, I have not figured out yet how to resolve this issue.
![Screenshot_20200518-132052](https://user-images.githubusercontent.com/44001310/82187868-aaa6c400-990a-11ea-940b-625bcbf986f6.png)

**Comment by mahmodHammad** [comment]
Are you working on it?

**Comment by abhinavsri360** [comment]
@mahmodHammad I mentioned in the comment above

**Comment by mahmodHammad** [comment]
for anyone will work on it here's a hint.
look for the @mediaquery ,inside it just remove the display none; 
if you are using vscode press CTRL + SHIFT + f , this will enable you to quickly search over all the project, so you can search with the className of the table,

**Comment by abhinavsri360** [comment]
thanks for the advice @mahmodHammad I have fixed the issue in #390

**Comment by YashKumarVerma** [comment]
> thanks for the advice @mahmodHammad I have fixed the issue in #390

Please fill the issue template

**Comment by abhinavsri360** [comment]
Filled @YashKumarVerma
