### ISSUE TITLE
Add applications of MUX and DEMUX

### ISSUE THREAD

**Issue by deepak2431** [CircuitVerse/Interactive-Book#32]
#### I am submitting a -
* [] **Feature Request**

#### Describe your bug/feature - 
The application of multiplexer and demultiplexer can be added to make the book more informative.

**Comment by satyamroy001** [comment]
i will do that, do i have to make circuit of mux and demux

**Comment by deepak2431** [comment]
@satyamroy001 No you don't need to make circuit for MUX and DEMUX.

**Comment by Prerna-0202** [comment]
I would like to work on this issue. Is anyone working on this issue?
