### ISSUE TITLE
Redesign the side-nav bar to include sub-topics for every main topic present

### ISSUE THREAD

**Issue by schezfaz** [CircuitVerse/Interactive-Book#329]
**Current Status:** 
The side nav-bar can be improved upon by standardizing it at par with the side nav-bar at the [CircuitVerse Docs page](https://docs.circuitverse.org/). In a sense that, all sub-topics within a broad main-topic can be navigated to easily from the nav-bar itself (as in the case of the docs page).

For example, the [Gates page](https://learn.circuitverse.org/docs/gates.html). To access the content for the AND gate or OR gate, one must first go the Gates page and then navigate from there. 

![image](https://user-images.githubusercontent.com/28871211/82439679-b33cfd00-9ab8-11ea-9857-2e20a0c2fcd7.png)

In the case of the [CircuitVerse Docs page](https://docs.circuitverse.org/), the user can navigate directly from the side nav-bar itself.

![image](https://user-images.githubusercontent.com/28871211/82439974-33636280-9ab9-11ea-849c-f5949467cf17.png)

**Enhancemnet**: 
Standardise the side-nav bar for  [CircuitVerse Docs page](https://docs.circuitverse.org/) in such a way that all sub-topics  are listed below main topics, similar to how the side-nav is designed for the CircuitVerse documentation page.

**Comment by YashKumarVerma** [comment]
are you working on it ?

**Comment by schezfaz** [comment]
I would like to!

**Comment by schezfaz** [comment]
not yet, but I would like to begin work on it once I complete working on [Issue #1439 ](https://github.com/CircuitVerse/CircuitVerse/issues/1439). Someone else can take it forward in the meantime, if not, I'll pick it up once I submit the PR for the above issue!

**Comment by ShubhankarKG** [comment]
I'm not sure if that is possible, because the docs and interactive-book are two different applications. The Table of Contents in the Interactive-book refer to links present within the same page. The navbar nests the link which have a common parent. Those are two separate things. I'd say since we already have a TOC, another nesting in the navbar isn't required.

**Comment by schezfaz** [comment]
Right, that's true. However, both CircuitVerseDocs and the Interactive Book are user-documentations, in the sense that if a user visits the CircuitVerse.org page, they are likely to access both these applications in order to find their way around. 

Since both these applications fall under the CircuitVerse.org suite, it would enhance the UI/UX if consistency is maintained throughout. The navigation aspect is just one such example where the continuity and consistency is disrupted. I just feel it would be better to keep the same standard across both applications.

However, that being said, it might be a bit of a task getting InteractiveBook and CircuitVerseDocs at par since docsify is currently not being implemented in InteractiveBook. Let's figure though.

**Comment by manjotsidhu** [comment]
Fixed by #460
