### ISSUE TITLE
O is not in center

### ISSUE THREAD

**Issue by dev9414** [CircuitVerse/Interactive-Book#33]
in msi components in multiplexer in circuit diagram 0 is touches to upper level box it should be in center

![Screenshot_20191106-013805](https://user-images.githubusercontent.com/46513305/68242337-573beb00-0036-11ea-97cb-487168411607.png)

**Comment by satu0king** [comment]
This is to do with the simulator itself and has to be changed at the simulator codebase and not the interactive book.
