### ISSUE TITLE
Add Documentation for "NAND Gate Method" to simplify a boolean function

### ISSUE THREAD

**Issue by schezfaz** [CircuitVerse/Interactive-Book#331]
**Current Status:** 
The [Boolean Function Page](https://learn.circuitverse.org/docs/bool2.html) cites two possible ways in which one can simplify a boolean function. The first being the K-Map method and the second being the NAND Gate method.

![image](https://user-images.githubusercontent.com/28871211/82442210-d7024200-9abc-11ea-829c-eb7a1bb7688d.png)

Currently, there is documentation present for only one of the methods mentioned i.e. the K-Map method. There is no furhter information given on how to implement the NAND Gate Method and thus, it is not hyperlinked.

**Enhancement:**
A new page documenting the implementation of the NAND Gate method for simplification of boolean expressions with appropriate explanations, steps, examples and gifs/images.

**Comment by schezfaz** [comment]
I would like to work on this!

**Comment by YashKumarVerma** [comment]
This can be helpful
- https://circuitverse.org/simulator/embed/42411

**Comment by schezfaz** [comment]
thankyou!
