### ISSUE TITLE
Activate the searchbar onclick

### ISSUE THREAD

**Issue by deepak2431** [CircuitVerse/Interactive-Book#34]
#### I am submitting a -
* [] **Feature Request**

#### Describe your bug/feature -
Implement feature to activate the search bar onClick. No results found should also be displayed for the contents not found in the book. This feature can also be implemented with the search bar.

**Comment by ankitkataria** [comment]
Addition of `No Results Found` for keywords that are not found will be a great idea.

**Comment by satu0king** [comment]
> Addition of No Results Found

This sounds good. @deepak2431  could you clarify what onClick is ?

**Comment by deepak2431** [comment]
@satu0king I will add a demo webiste for this purpose. As I mean to activate the searchbar while entering the search keywords.

**Comment by deepak2431** [comment]
@satu0king You can check the search bar of this website as it gets activates on hover.
https://www.solodev.com/blog/web-design/how-to-add-expandable-site-search-to-your-navigation.stml

**Comment by Brownie-in-Motion** [comment]
Can you give some more information about what this means? I don't see the behavior you are describing.

**Comment by deepak2431** [comment]
> Can you give some more information about what this means? I don't see the behavior you are describing.

Can you test the search bar of this website https://www.solodev.com/blog/web-design/how-to-add-expandable-site-search-to-your-navigation.stml
You can see that when you click on the search bar the color changes to light blue. I am expecting the same behaviour to the search bar of Interactive Book after completion of this task.
Thanks!

**Comment by abhinavsri360** [comment]
@YashKumarVerma 😅 
Lot's of useless issues open

**Comment by YashKumarVerma** [comment]
> @YashKumarVerma 😅 
> Lot's of useless issues open

Useless as in ?
If you find any issue that must be closed, just drop a comment with mention

**Comment by abhinavsri360** [comment]
Ohh, I meant the same.
Please review and close this issue as this seems to be resolved, because search bar activates when clicked.
Thanks,
@YashKumarVerma

**Comment by manjotsidhu** [comment]
Fixed by #460
