### ISSUE TITLE
Mounting of Boolean function page

### ISSUE THREAD

**Issue by abhinavsri360** [CircuitVerse/Interactive-Book#357]
## Describe the bug
The Boolean functions page by default mounts at Truth Table generator. No idea why, works fine on my local machine i.e., mounts at the top of the page. Whereas at https://learn.circuitverse.org/docs/bool2.html is not mounted at the top of the page.

## To Reproduce
I am still trying to figure out how to fix this as this works fine on my local machine.

## Expected behavior
The page should be mounted at the top.

## Screenshots
https://learn.circuitverse.org/docs/bool2.html
Go to the link you'll get my bug.

## Additional context
I am not working on the issue.

**Comment by YashKumarVerma** [comment]
I was unable to reproduce the issue. Could you please help

**Comment by Shivansh2407** [comment]
I think I got his issue @YashKumarVerma. Basically @abhinavsri360 is trying to say that when we open any specific page of Interactive book, then we start from the top of Page where TOC and all is present but specifically on opening this page we get to see the truth table generator (the last section of the page) directly. The user has to scroll up to view the contents of the Page. 
Please try to completely describe the issue attaching a screenshot or screen recording, this helps the contributor to understand the issue and fix it faster.

**Comment by abhinavsri360** [comment]
Sure, @Shivansh2407 I will add a screen recording.

**Comment by rishabhgit0608** [comment]
hello this issue is fixed

**Comment by abhinavsri360** [comment]
Hey, @rishabhgit0608 thanks for notifying, closing this issue, also, is there a PR associated with this issue such that I can link the same and close this, if you know that lemme know, I'll close this!
Thanks!
