### ISSUE TITLE
Docs: In general, use second person instead of first person

### ISSUE THREAD

**Issue by Dishebh** [CircuitVerse/Interactive-Book#373]
## Is your feature request related to a problem? Please describe.
As per the [Google style guide](https://developers.google.com/style/person), we should prefer using second person in the docs rather than the first person as the docs are intended to be used by the end-user.

## Describe the solution you'd like
Replace all the first-person terms to second-person.

## Would you like to work on it?
Yes

**Comment by Dishebh** [comment]
@YashKumarVerma @Shivansh2407 Shall I work on it if it complies with the existing style guide?

**Comment by YashKumarVerma** [comment]
> @YashKumarVerma @Shivansh2407 Shall I work on it if it complies with the existing style guide?

I think it can be done
