### ISSUE TITLE
Dark Mode Button does not works properly on refresh

### ISSUE THREAD

**Issue by Shivansh2407** [CircuitVerse/Interactive-Book#376]
## Describe the bug
Whenever the dark mode is selected by the user, on refreshing the page, Dark mode is retained but the text on the button switches back to Dark Mode instead of Light Mode.

## To Reproduce

1.  Go to 'https://learn.circuitverse.org/'
2.  Click on 'Dark Mode'
3.  Refresh The Page
4.  See error

## Expected behavior

It should display Light Mode Text on the button when Dark Mode is selected and the Page is refreshed.

## Desktop (please complete the following information):

* OS: [Windows 10]
* Browser [Chrome]

I am not working on this Issue. If anyone wants to work, Please comment below and this issue will be assigned to you 👍

**Comment by Shivansh2407** [comment]
![DarkMode1](https://user-images.githubusercontent.com/42182955/82993776-c30b9280-a01e-11ea-86af-14310229b1e7.gif)
Uploaded Screen Recording for Better Understanding

**Comment by YashKumarVerma** [comment]
Okey, the reason for it is [most probably] that we're relying on local storage and not session storage. 

Whoever is working to solve this one, make sure you give a good read to this one.
https://stackoverflow.com/a/19869560/5131640
