### ISSUE TITLE
Doc: Use sentence cases in titles and headings

### ISSUE THREAD

**Issue by Dishebh** [CircuitVerse/Interactive-Book#378]
## Is your feature request related to a problem? Please describe.

If we follow the [Google developers style guide](https://developers.google.com/style/capitalization), we should use sentence cases for all our headings and titles (with added exceptions).

## Describe the solution you'd like

Use sentence cases for titles and headings.

## Would you like to work on it?
Yes

**Comment by Dishebh** [comment]
cc: @YashKumarVerma @Shivansh2407 

Please see if the issue can be worked upon to improve the docs.

**Comment by YashKumarVerma** [comment]
uniformity is good.

**Comment by Dishebh** [comment]
Working on it, then
