### ISSUE TITLE
Add a NOR gate method to the sidebar?

### ISSUE THREAD

**Issue by Dishebh** [CircuitVerse/Interactive-Book#384]
## Is your feature request related to a problem? Please describe.
Add a NOR gate method to the sidebar? (As a complementary feature to the current NAND gate method, since they both are universal gates).

## Would you like to work on it?
Yes

**Comment by Dishebh** [comment]
@YashKumarVerma @Shivansh2407 please let me know if I can work on it.

**Comment by Shivansh2407** [comment]
Yes @Dishebh. Go ahead and make a PR.
