### ISSUE TITLE
TOC missing on some pages

### ISSUE THREAD

**Issue by abhinavsri360** [CircuitVerse/Interactive-Book#388]
## Describe the bug

Table of contents is missing on the following pages: Binary Numbers, Digital Sequential circuits, Race around condition, 
## To Reproduce

Can be done via adding {:toc} on top of the page

## Expected behavior
TOC must be present on these pages

## Additional context
I am working on this issue

**Comment by YashKumarVerma** [comment]
Please follow the issue template.

**Comment by abhinavsri360** [comment]
Did not got you, what am I supposed to rectify?

**Comment by YashKumarVerma** [comment]
> Did not got you, what am I supposed to rectify?

![image](https://user-images.githubusercontent.com/14032427/83361458-bd0f0c00-a3a6-11ea-95e1-58e20a9bde59.png)

Consider removing unwanted lines from here

**Comment by abhinavsri360** [comment]
Updated
