### ISSUE TITLE
Previous and next buttons

### ISSUE THREAD

**Issue by abhinavsri360** [CircuitVerse/Interactive-Book#391]
## Describe the bug
Previous and Next buttons on the page Boolean Algebra

## Expected behavior
Must be present in the next line with space in between

## Screenshots
![image](https://user-images.githubusercontent.com/44001310/83351934-bf9d4180-a365-11ea-96e9-1925b88c7a4b.png)

## Additional context
I am not working on this bug

**Comment by YashKumarVerma** [comment]
Thanks for pointing out, can you remove the unwanted data from the template. :+1

**Comment by abhinavsri360** [comment]
Sure Why not!

**Comment by i-m-vivek** [comment]
@abhinavsri360 Can I work on this issue?

**Comment by abhinavsri360** [comment]
Yeah sure

**Comment by i-m-vivek** [comment]
![Capture](https://user-images.githubusercontent.com/56120485/83376683-c02eea00-a3f0-11ea-8eb4-7b836fc8888c.JPG)

@YashKumarVerma Is this Okay?

**Comment by YashKumarVerma** [comment]
> ![Capture](https://user-images.githubusercontent.com/56120485/83376683-c02eea00-a3f0-11ea-8eb4-7b836fc8888c.JPG)
> 
> @YashKumarVerma Is this Okay?

Looks good, send a PR and mention in commit / pr body that `Fixes #391`
