### ISSUE TITLE
Pop Quizzes Not Working in Dark Mode

### ISSUE THREAD

**Issue by Shivansh2407** [CircuitVerse/Interactive-Book#395]
## Describe the bug
The Pop Quiz in the Binary Page works well in the light mode but needs to be fixed in the dark mode.

## To Reproduce

1.  Go to 'https://learn.circuitverse.org/docs/binary.html'
2.  Click on 'Dark Mode'
3.  Scroll down to 'Pop Quiz'
4.  See error

## Expected behavior

It should work with the Dark Mode matching the theme of Circuitverse.

## Screenshots

Light Mode 
![image](https://user-images.githubusercontent.com/42182955/83403680-c5a72700-a426-11ea-9a25-48752a47958e.png)

Dark Mode 

![image](https://user-images.githubusercontent.com/42182955/83403719-d6579d00-a426-11ea-9274-4cd49b8f55ab.png)

## Desktop (please complete the following information):

* OS: [Windows]
* Browser [Chrome]

I am Not Working on this Issue. Please comment if you want to work on this issue.

**Comment by nileshdas** [comment]
Hi! Can I work on this issue?

**Comment by Shivansh2407** [comment]
Sure @nileshdas . Go ahead and Make a PR 👍.
