### ISSUE TITLE
Add binary labels to the interactive K-Map

### ISSUE THREAD

**Issue by sal2701** [CircuitVerse/Interactive-Book#4]
**Is your feature request related to a problem? Please describe.**
Most of the learning resources including the tutorial on the website use 0's and 1's as labels to teach students about K-map. So, the same system implemented here will be useful and convenient for everyone

**Describe the solution you'd like**
0's and 1's should also be displayed along with the lines around the K-map for convenience

**Describe alternatives you've considered**
I am planning on displaying binary numbers below the lines used to indicate the variable. 

**Are you working on this? (Yes/No)**
Yes

**Comment by satu0king** [comment]
@Amansingla97 please help @sal2701 out with the kmap code. Also @sal2701 note that the user can hover on any cell and it shows the values.

**Comment by sal2701** [comment]
@satu0king if we think from the point of view of a learner, they might not find the lines indicating 1's as intuitive as the binary numbers. Also since the previous module teaches using 1's and 0's, consistency in the tables will help them learn better. This is what I and a few of my friends who tried it out feel. We can even add a toggle if necessary

**Comment by satu0king** [comment]
Yes a toggle is good

**Comment by sal2701** [comment]
Okay, so I'll start working on it and ask if I have any doubts

**Comment by Amansingla97** [comment]
gr8
