### ISSUE TITLE
Table elements alignment in all pages

### ISSUE THREAD

**Issue by Dishebh** [CircuitVerse/Interactive-Book#407]
## Is your feature request related to a problem? Please describe.
There are some tables where its values are left-aligned, while some tables where their values are center-aligned.

### Table where its values are left-aligned:
![Screenshot from 2020-06-05 18-42-47](https://user-images.githubusercontent.com/43489708/83880195-6c0f6700-a75c-11ea-8efd-366e68e09da8.png)

### Table where its values are center-aligned:
![Screenshot from 2020-06-05 18-42-55](https://user-images.githubusercontent.com/43489708/83880205-6dd92a80-a75c-11ea-9bb7-6bc0326627b1.png)

## Describe the solution you'd like
Either make:
- All the values left-aligned.
- All the values center-aligned.
- All the truth tables' data center-aligned, and the tables that have more descriptive text within them left-aligned; or vice-versa.

**Comment by Dishebh** [comment]
cc: @Shivansh2407 @abhinavsri360 @schezfaz

**Comment by abhinavsri360** [comment]
@Dishebh please make the issue headline more specific something like 'Table elements alignment in all pages' and remove the question mark as well.

**Comment by manjotsidhu** [comment]
Fixed by #460
