### ISSUE TITLE
Uneven styling in "Operators in Binary"

### ISSUE THREAD

**Issue by nileshdas** [CircuitVerse/Interactive-Book#409]
## Describe the bug

The bitwise operators are very unevenly designed

## To Reproduce

1.  Go to 'https://learn.circuitverse.org/docs/binary2.html'
2.  Scroll down to 'Bitwise Operators'
3.  See the uneven styling and odd big operator selector button

## Expected behavior

The answer boxes should be evenly sized and the operator selector button should be a little smaller.

## Screenshots

![Screenshot (125)](https://user-images.githubusercontent.com/39062229/83903171-49d91180-a77b-11ea-9627-29c29222d222.png)

## Desktop (please complete the following information):

* OS: [ windpws]
* Browser [chrome]

**Comment by nileshdas** [comment]
I am working on this issue

**Comment by abhinavsri360** [comment]
@nileshdas every time you don't need to ask to work on an issue that you opened. Just mention in the template that you are working or not. If you find an issue on which no one is working just add a comment on that issue stating 'I am on it' and simply start working.

**Comment by abhinavsri360** [comment]
@nileshdas please update the issue template if you are working on this issue.

**Comment by nileshdas** [comment]
I am working on it

**Comment by b30wulffz** [comment]
@Shivansh2407 This issue can be closed now.

**Comment by Shivansh2407** [comment]
Closing this as the UI of the tool has been revamped in #437
