### ISSUE TITLE
Race around condition

### ISSUE THREAD

**Issue by dev9414** [CircuitVerse/Interactive-Book#41]
Feature request:
There is no explanation of race around or racing condition of JK FLIP FLOP

**Comment by satu0king** [comment]
Race condition can be added as separate chapter on its own.

**Comment by ericsheng495** [comment]
Question, do we have to make a pull request and integrate the stuff to the website or can we just write it in a google doc?

**Comment by Ananthavijay** [comment]
@ericsheng495 you should add it in the interactive book, so you should make a PR
