### ISSUE TITLE
Rounded rectangles when using Interactive Karnaugh Map disappear in Dark Mode

### ISSUE THREAD

**Issue by nileshdas** [CircuitVerse/Interactive-Book#418]
## Describe the bug

Rounded rectangles when using Interactive Karnaugh Map disappear in Dark Mode

## To Reproduce

1.  Go to 'https://learn.circuitverse.org/docs/kmapi.html'
2.  Click on 'Dark Mode'
3.  Click on 'Random Example'
4.  See error

## Expected behavior

The rectangles should appear so as to give a better idea about Karnaugh maps

## Screenshots
![Screenshot (143)](https://user-images.githubusercontent.com/39062229/83973361-8d5e8780-a903-11ea-954b-471e489258bb.png)
![Screenshot (144)](https://user-images.githubusercontent.com/39062229/83973365-92bbd200-a903-11ea-984c-79481b234763.png)

## Desktop (please complete the following information):

* OS: [Windows]
* Browser [Chrome]

## Additional context
Would like to propose these changes
![Screenshot (145)](https://user-images.githubusercontent.com/39062229/83973387-b41cbe00-a903-11ea-922d-2d02496edf85.png)

![Screenshot (146)](https://user-images.githubusercontent.com/39062229/83973390-b717ae80-a903-11ea-86a9-d7189b7c5369.png)
I am working on it

**Comment by b30wulffz** [comment]
@nileshdas Better. 
@abhinavsri360 @YashKumarVerma Please have a look.
