### ISSUE TITLE
Fix Grammatical Errors in the Interactive Book

### ISSUE THREAD

**Issue by NitishGadangi** [CircuitVerse/Interactive-Book#422]
## Describe the bug

There are several Grammatical errors on each page of the Interactive Book. Namely,
- Spelling Mistakes
- Misplaced Modifiers
- Pronoun Disagreement
- Misplacing Commas
- and other minor errors.

These errors must be fixed as they might cause unclear communication between the author and the reader.

## Additional context

**I will be working on this issue.**

I have added a check list below and will be updating them regularly after fixing errors in each page.
- [x] Home
- [x] Binary numbers
- [x] Operators in binary numbers
- [x] Gates
- [x] Interactive gates
- [x] Universal gates
- [x] Basic applications
- [x] Boolean algebra
- [x] Boolean function
- [x] K-maps
- [x] Interactive k-map
- [x] Combinational logic
- [ ] ALU
- [ ] MSI Components
- [ ] Clock signal and triggering
- [ ] Digital sequential circuits
- [ ] Latches
- [ ] Flipflop integration
- [ ] Flipflops
- [ ] Race around condition
- [ ] Digital registers
- [ ] Application of shift registers
- [ ] Digital counters
- [ ] FSM
- [ ] Interactive FSM

Please don't close this issue until all the contents are free from grammatical errors. So that we can link all the related PRs to this issue one by one.

**Comment by NitishGadangi** [comment]
I will be using Grammarly to Manually fix errors on each page.

**Comment by NitishGadangi** [comment]
@YashKumarVerma  Bro,
As you have mentioned in the PRs

>Please check if the content is genuine or from other sources. We are replacing any plagiarized content, and therefore any fixes to it are not appreciated, as they would be overwritten in the near future.

Does this mean, it's currently not necessary to check for grammatical errors? <br>
OR
Should I make a plagiarism check and make necessary changes to the content before applying grammatical corrections

**Comment by YashKumarVerma** [comment]
> Should I make a plagiarism check and make necessary changes to the content before applying grammatical corrections

I think this would be better.

**Comment by b30wulffz** [comment]
Good job.
But I don't see any point making multiple PRs for the same issue.
Sending a PR with all the changes in different commits, and then squashing those commits into one would do the work.
@YashKumarVerma @Shivansh2407 What are your views about this?

**Comment by abhinavsri360** [comment]
There is always an issue #92 opened for the same reason. @NitishGadangi did you properly read the issue template?

**Comment by NitishGadangi** [comment]
> There is always an issue #92 opened for the same reason. @NitishGadangi did you properly read the issue template?

Hey @abhinavsri360 ,
I got you but, I think there is huge difference between correcting spelling mistakes and fixing grammatical errors.

**Comment by NitishGadangi** [comment]
> Good job.
> But I don't see any point making multiple PRs for the same issue.
> Sending a PR with all the changes in different commits, and then squashing those commits into one would do the work.
> @YashKumarVerma @Shivansh2407 What are your views about this?

@b30wulffz 
So The reason I am making multiple PRs is to keep track of each file/topic individually.
And its actually a better practice to do so. Reason, if we want we can revert changes made that particular file without affecting the other files.

For more clarification you can refer to the PRs made by others to fix plagiarism in #92

**Comment by YashKumarVerma** [comment]
@NitishGadangi you're using Grammarly to fix these errors right?

**Comment by NitishGadangi** [comment]
> @NitishGadangi you're using Grammarly to fix these errors right?

Yes bro

**Comment by abhinavsri360** [comment]
> > There is always an issue #92 opened for the same reason. @NitishGadangi did you properly read the issue template?
> 
> Hey @abhinavsri360 ,
> I got you but, I think there is huge difference between correcting just the spelling mistakes and fixing grammatical errors.

I understand @NitishGadangi  but this could have been an extended version of the same, you could have added your checkbox chart in the same issue. Also, lots of PR doesn't make any sense you can keep a check simply from your checkbox chart if you say that it is created to track the progress of work.

**Comment by YashKumarVerma** [comment]
Closing it in favor of #80 as it is difficult to track like this.

Once the file would be fixed for grammatical errors in current versions and then for fixing plagiarism (essentially rewritten from top to bottom) and most probably making the changes done for this issue ineffective. 

So it would be in the best interest of the contributions, the maintainers, and the project history for this to be done integrated.

**Comment by YashKumarVerma** [comment]
With this issue closed, the PR's that were made for this should ideally be closed.
