### ISSUE TITLE
Redesigning of and/or/xor tool in binary2.html

### ISSUE THREAD

**Issue by b30wulffz** [CircuitVerse/Interactive-Book#433]
## Is your feature request related to a problem? Please describe.

Previous and/or/xor tool has issues while using on mobile i.e. it is not available for mobile. Plus it does not match with the UI of the webpage.
This is how it looks right now:
![image](https://user-images.githubusercontent.com/31105595/84125673-826a3b00-aa5a-11ea-8f25-2a316e3cad6d.png)

## Describe the solution you'd like

I previously worked on binary to decimal convertor in binary.html which looks like this: 
![image](https://user-images.githubusercontent.com/31105595/84125171-cd378300-aa59-11ea-8b25-35c12526f6d0.png)
Hence I decided to follow a similar layout while redesigning this tool so that it perfectly fits the UI and is responsive on different screen sizes.

## Describe alternatives you've considered

.None

## Additional context

Here is a rough design of the same that I am going to implement:
![and/or/xor tool](https://user-images.githubusercontent.com/31105595/84125255-e9d3bb00-aa59-11ea-8e2a-126572d33b46.jpeg)
Feedback for new design welcomed.

**Comment by Shivansh2407** [comment]
What I can make from the rough design is really a cool UI. Please finish the development work soon and open up a PR for the same.

**Comment by YashKumarVerma** [comment]
Really liked the way he showed the prototype :smile:
