### ISSUE TITLE
Issue with XOR operator of and/or/xor tool

### ISSUE THREAD

**Issue by b30wulffz** [CircuitVerse/Interactive-Book#440]
## Describe the bug

If only one bit is toggled to 1 and then back to 0, and the operator is set on xor, it will show 1 which is wrong. 
This is because the array which is storing bits in the form of true and false is not initialized. Hence it is storing an empty value in the beginning. If only one of the bit is toggled to 1 and again toggled to 0, the array stores one value as false, and false != empty.

## To Reproduce

1.  Go to 'https://learn.circuitverse.org/docs/binary2.html'
2.  Scroll down to and/or/xor tool
3.  Set operator to xor
4.  Now in any one column, toggle only one bit to 1 and then back to 0, do not touch other bit (let it be 0)
5.  Output will be 1 which is wrong.

## Expected behavior

For 0 ^ 0 
Output should be 0.

## Screenshots

![video](https://user-images.githubusercontent.com/31105595/84274237-3e0b9780-ab4d-11ea-9663-4750a2f885b4.gif)

## Desktop (please complete the following information):

* OS: Windows 10
* Browser: Google Chrome
* Version: 83.0.4103.97

## Smartphone (please complete the following information):

* Device: Pocophone F1
* OS: Android 10
* Browser: Google Chrome
* Version: 80.0.3987.132

## Additional context

I have fixed this issue.

**Comment by YashKumarVerma** [comment]
A nicely written issue report. Good work !

**Comment by b30wulffz** [comment]
Thanks @YashKumarVerma :)
