### ISSUE TITLE
State Table Generator Not Accessible in Mobile

### ISSUE THREAD

**Issue by Shivansh2407** [CircuitVerse/Interactive-Book#443]
## Describe the bug
The State Table Generator in flipflop2 page needs to be changed as it is available currently on desktop view. If the User wants to access it through mobile then it asks for pressing F and there is no keyboard that pops up on page load. 

## To Reproduce

1. Go to 'https://learn.circuitverse.org/docs/flipflop2.html'
2. Use Mobile View
3. See error

## Expected behavior
We need to change the press F functionality to a button, so that the user can start the table generation or the keyboard should pop up on page load in mobile view.

## Screenshots
Desktop View : 
![image](https://user-images.githubusercontent.com/42182955/84483968-b726fe00-acb7-11ea-9ba5-f82df15fa328.png)

Mobile View :
![image](https://user-images.githubusercontent.com/42182955/84484181-05d49800-acb8-11ea-8928-99c107fba0fb.png)

## Desktop (please complete the following information):

* OS: [Windows 10]
* Browser [Chrome]

## Smartphone (please complete the following information):

* OS: [Android]
* Browser [Chrome]

## Additional context

The Navbar needs to fixed in the Mobile View as it is a bit shifted from its original positionas in the other pages. 

I am not working on the Issue. Please comment below to work on it.

**Comment by b30wulffz** [comment]
Alignment issue, doesn't looks good.
![image](https://user-images.githubusercontent.com/31105595/84510541-e56e0300-ace2-11ea-9093-9f4c74a865e9.png)

Can be fixed, will do it by tomorrow.

**Comment by b30wulffz** [comment]
Can be fixed. Will do it by tomorrow.

**Comment by b30wulffz** [comment]
@Shivansh2407 
Should I remove press F functionality completely as it doesn't make any sense? Instead keep a button

**Comment by Shivansh2407** [comment]
I think we should keep a button instead of the press F functionality .@YashKumarVerma what are your views?

**Comment by b30wulffz** [comment]
@Shivansh2407 @YashKumarVerma 
Minor updates. Is this design okay?

![ezgif com-video-to-gif (5)](https://user-images.githubusercontent.com/31105595/84572031-f9823500-adb4-11ea-8893-00cbe68cc190.gif)

This is a basic change, planning to do some more including:
- fixing button which looks a bit small,
- fixing colour combination,
- fixing the overflowing dropdown menu.

PS: Forgot to make mouse visible in the video.

**Comment by Shivansh2407** [comment]
It is really good @b30wulffz. Make a PR so that we can give our views on it 👍
