### ISSUE TITLE
Show alert instead of undefined behavior.

### ISSUE THREAD

**Issue by YashKumarVerma** [CircuitVerse/Interactive-Book#445]
Nice Work @b30wulffz 👍 
We Also need to fix the table generated after filling the drop-downs, as sometimes we get undefined. An alert should be displayed instead of showing undefined in the table. We need to do that in a different PR.

_Originally posted by @Shivansh2407 in https://github.com/CircuitVerse/Interactive-Book/pull/444#issuecomment-643951084_

**Comment by b30wulffz** [comment]
@Shivansh2407 @YashKumarVerma Can you give me steps to regenerate this bug?

**Comment by Shivansh2407** [comment]
Screen Recording :
![20200619_103223](https://user-images.githubusercontent.com/42182955/85098431-5b5cf780-b218-11ea-92b9-975ff2fbbc6f.gif)

We Should not show this undefined in the tables, It does not looks good and will give the user a bad experience whenever they see Undefined filled in the tables, rather we can display an alert before generating the table and display the table only when all the conditions are fulfilled.
See the Above screen recording for regenerating this bug

**Comment by animesh-007** [comment]
Can I work on this?

**Comment by b30wulffz** [comment]
@animesh-007 Yes, sure.
