### ISSUE TITLE
Top Bar buttons issue

### ISSUE THREAD

**Issue by coding-CEO** [CircuitVerse/Interactive-Book#446]
## Describe the bug

When we newly visit the website, the buttons on the top bar doesn't get proper styling. But, if we refresh the page it gets normal.

## To Reproduce
Copy link of any page, specially Boolean function page and paste that link in a new tab, you will see the problem on top bar.

1.  Copy link of Boolean function page
2.  Open a new tab
3.  Paste the link and don't refresh Page.
4.  See error on top bar.

## Expected behavior

Styling of buttons should be normal.

## Screenshots

![Screenshot_2020-06-24-20-38-05-913~2](https://user-images.githubusercontent.com/52625909/85585202-6b803700-b65d-11ea-9eaa-fedb53e31f67.jpeg)

## Smartphone (please complete the following information):

* Device: Lenovo
* OS: Android 7.0
* Browser: chrome
* Version: -

## Additional context

I produced this issue on my mobile with desktop mode. So, don't know if this issue exist in PC.

Anyone can work on this issue :+1:

**Comment by Roshan13046** [comment]
This issue doesn't exist in PC.

**Comment by Vishal-raj-1** [comment]
@coding-CEO I have check it several time !! There is no such error. Maintainer can close this issue.

**Comment by manjotsidhu** [comment]
Fixed by #460
