### ISSUE TITLE
Add binary number representation details

### ISSUE THREAD

**Issue by deepak2431** [CircuitVerse/Interactive-Book#45]
#### I am submitting a -
* [] **Feature Request** 

#### Describe your bug/feature -
Detailed explanation about unsigned and signed numbers and representation of binary numbers into signed and unsigned form can be added.

**Comment by abhinavsri360** [comment]
Resolved in #280

**Comment by coding-CEO** [comment]
@YashKumarVerma Close this issue.

**Comment by mahmodHammad** [comment]
@abhinavsri360 
https://github.com/CircuitVerse/Interactive-Book/pull/280 for this issue, cause you did not mention unsigned and signed numbers, however, your PR introduced an introduction to Binary number which was good 👍
