### ISSUE TITLE
Make References' page more informative

### ISSUE THREAD

**Issue by schezfaz** [CircuitVerse/Interactive-Book#454]
## Current Status
Currently the [References](https://learn.circuitverse.org/references) page only has a bunch of links mentioned, without giving the reader any context on what they can find at which link, or how the link or resource could be further utilised by them.
 
## Enhancement
Make the references page more information by adding:
- Context for each hyperlink
- Adding a title for each hyperlink i.e. instead of having the whole url written, embedd the link within a clickable title
- Links to more resources for further reading on Computer Organisation and Digital Logic Design

Not working on this currently.

**Comment by divanshisethi9488** [comment]
Can i work on this?

**Comment by YashKumarVerma** [comment]
@divanshisethi9488  if @schezfaz is not, you surely can.
Before starting anything, please get confirmation from @schezfaz

**Comment by schezfaz** [comment]
Hi @divanshisethi9488, I haven't started working on this issue yet,  you can go ahead and take it up!!

**Comment by divanshisethi9488** [comment]
Thankyou, I will begin working on it.

**Comment by kunbeg** [comment]
@schezfaz can I work on this issue? I have checked for any open pull request associated with this issue. I didn't find any since this is issue was opened and this is good for me as I'm a new contributor.

**Comment by chinmaym07** [comment]
@schezfaz can O work on this .?

**Comment by pavanjoshi914** [comment]
@schezfaz I think this beta version of this books has fixed this problem and can be closed ,thanks 
vist this :https://betalearn.circuitverse.org/docs/binary-algebra/boolean-functions.html#references

**Comment by Shivansh2407** [comment]
Updated in GSOD 2020 Branch
