### ISSUE TITLE
Dynamic Height of the Search Drop-Down

### ISSUE THREAD

**Issue by Shivansh2407** [CircuitVerse/Interactive-Book#456]
## Describe the bug
When the number of elements in the drop down are less(1-2), the drop down should not be fixed to its length, it should rather be dynamic while changing the length up to some specific rows of results.
Please see the image for more clear idea. This white space does not provide a good user experience.
https://github.com/CircuitVerse/Interactive-Book/pull/455#pullrequestreview-480488659
## To Reproduce

1. Go to 'learn.circuitverse.org'
2. Click on 'Search'
3. Type Something in the search bar

## Expected behavior

The Height should be restricted to show at max of 5 search results, but if less than 5 results are available, then the height should automatically change depending on the results

## Screenshots
![image](https://user-images.githubusercontent.com/42182955/91935508-7addc980-ed0b-11ea-8cad-04262f1c31a0.png)

## Desktop (please complete the following information):

* OS: [Windows 10]
* Browser [Chrome]

**Comment by shubhdeep123** [comment]
@Shivansh2407 looking to work on this issue.

**Comment by Shivansh2407** [comment]
Yeah sure @shubhdeep123 . Go ahead and shoot a PR 👍
