### ISSUE TITLE
Animations of universal gates docs are not mobile responsive.

### ISSUE THREAD

**Issue by shubhdeep123** [CircuitVerse/Interactive-Book#458]
## Describe the bug
In universal gate docs animated implementation of gates are not mobile responsive.

## To Reproduce

1.  Go to https://learn.circuitverse.org/docs/universal_gates.html
2.  Scroll down in mobile view
3.  See error

## Expected behavior

Animations should be mobile responsive to fit properly in screen.

## Screenshots:

![Screenshot_2020-09-12-15-17-56-66](https://user-images.githubusercontent.com/64921946/92992969-13dec280-f50c-11ea-97ff-1607351efa01.jpg)

## Desktop:

* OS: [linux]
* Browser [chrome]

## Smartphone:

* Device: [realme XT]
* OS: [Android 10]
* Browser [Chrome]

**Comment by anushri20** [comment]
@shubhdeep123 Can i work on this?

**Comment by shubhdeep123** [comment]
Hey @anushri20 sure go ahead

**Comment by manjotsidhu** [comment]
Fixed by #460
