### ISSUE TITLE
Some docs have non-responsive elements.

### ISSUE THREAD

**Issue by shubhdeep123** [CircuitVerse/Interactive-Book#464]
## Describe the bug

Universal gate,NAND gate methods, NOR gate methods and Interactive FSM docs all have frame and svg elements that are not responsive for mobile.

## To Reproduce

1.  Go to 'https://learn.circuitverse.org/'
2.  Click on 'Menu'
3.  Go to above given Docs
4.  See error

## Expected behavior

Frame and svg elements should be responsive for Mobile.

## Screenshots

![universal Gate](https://user-images.githubusercontent.com/64921946/94669313-b382ba00-032e-11eb-8e5c-8d21b0b59274.jpeg)
![Nand gate method](https://user-images.githubusercontent.com/64921946/94669319-b5e51400-032e-11eb-9a96-8052d7b96568.jpeg)
![Nor gate method](https://user-images.githubusercontent.com/64921946/94669327-b7164100-032e-11eb-8fa5-a7b6ecd8e627.jpeg)
![interactive FSM](https://user-images.githubusercontent.com/64921946/94669331-b7aed780-032e-11eb-8806-cf507d25860a.jpeg)

## Desktop (please complete the following information):

* OS: [Ubuntu]
* Browser [chrome]

## Smartphone (please complete the following information):

* Device: [Realme xt]
* OS: [Android 10]
* Browser [Chrome]

**Comment by anushri20** [comment]
Is this open?

**Comment by anushri20** [comment]
@shubhdeep123 Is this open?

**Comment by Shivansh2407** [comment]
Hi @anushri20 , there are currently a lot of changes going in the CodeBase (see GSOD2020 branch) . During this time, we will not be merging any PRs, but after the GSOD 2020 branch gets merged, you can start Contributing to the New and enhanced Book

**Comment by anushri20** [comment]
Okay, thanks!

**Comment by manjotsidhu** [comment]
Fixed by #460
