### ISSUE TITLE
Button text is not properly aligned.

### ISSUE THREAD

**Issue by harshitaaaaaa** [CircuitVerse/Interactive-Book#471]
![Screenshot from 2020-10-06 01-39-25](https://user-images.githubusercontent.com/66556662/95127224-4aa7a180-0775-11eb-8daa-23e9f7516153.png)
Here, the text is not properly centered and the button size is small which doesn't seems good.
Also the white color of text inside the button is not perfectly visible.
I think it should be fixed!

**Comment by DhairyaBahl** [comment]
@harshitaaaaaa I would like to work on this issue. Kindly assign it to me.

Thanks :)

**Comment by harshitaaaaaa** [comment]
@DhairyaBahl Okay go ahead!

**Comment by yuktibagrodia** [comment]
can I do it? If it's not done yet?

**Comment by DhairyaBahl** [comment]
@yuktibagrodia From my side its free. I am not working on it currently :).

**Comment by yuktibagrodia** [comment]
#477 @harshitaaaaaa please check. changes are done only for button size and color. please tell me which text is not centered properly?

**Comment by Vishal-raj-1** [comment]
@harshitaaaaaa I would like to resolve this issue.

**Comment by Ayushgup85** [comment]
May i work on this issue?

**Comment by pavanjoshi914** [comment]
I think it looks good on beta version of this docs i.e gsod2020. @harshitaaaaaa you can close this issue. @Shivansh2407 any inputs here?

**Comment by manjotsidhu** [comment]
Fixed by #460
