### ISSUE TITLE
CSS styles for the new version (GSoD2020) of the Interactive Book

### ISSUE THREAD

**Issue by danielluehr** [CircuitVerse/Interactive-Book#475]
## Describe the bug

The new version of the book (being developed under the GSoD 2020 project) replaced the old version Just-the-docs (JTD) Jekyll theme, which was installed locally and included styling and structure hardcoded into it, with the current upstream JTD version installed as a Gem/plugin for Jekyll. In the process some of the original style of the book was lost, either because it was hardcoded in the template, or because it was closely related to document structures which are not now part of theme.

At least, the following problems with the style have been identified (there might be more). Check the attached screenshot for details (left is the pre-GSoD2020 version, right is the new version):

1. In the navigation bar, single pages at the top level and chapters (group of pages) have different "indentation" ("yellowish" 1 in the screenshot).
2. In the navbar, the distance from the bullet marker to the text is larger than in the original design (red 2 in the screenshot).
3. Chapter title is located more to the right than the sections in the chapter. Also, the section title style seems be a bit of with respect to the rest of the nav bar: i.e. color, marker, etc., although it is the same in the current version's style. (blue 3 in the screenshot).
4. Links at the top right are no longer buttons (they are part of the JTD theme) but they can be styled as such, it just need the proper CSS code (red 4 in the screenshot).
5. Table of content headline doesn't match the original book style. (Blue 5 in the screenshot).

## Expected behavior

Consistent style and closer to the current one

## Screenshots

![CVIB_versus-2020-10-07_labels](https://user-images.githubusercontent.com/20018048/95382743-800cd600-08c0-11eb-95cc-60fdb3202f51.png)

## Additional context

All css should go in the `_sass/custom/custom.scss` as indicated in the JTD [documentation](https://pmarsceill.github.io/just-the-docs/docs/customization/#override-and-completely-custom-styles)

See PR #474

**Comment by anushri20** [comment]
Can I work on this?

**Comment by Shivansh2407** [comment]
Yes @anushri20 go ahead 👍

**Comment by saumyasrivastava08** [comment]
Can i work on this

**Comment by AdityaTeltia** [comment]
Is this issue still open ? And can I work on it ? @danielluehr @Shivansh2407

**Comment by AdityaTeltia** [comment]
![SWOC](https://user-images.githubusercontent.com/67232537/103151516-b01f9300-47a4-11eb-92b5-1302cad48236.JPG)
We can do like in the picture to solve the 3 point of this issue . Tell if I can make a pr? @danielluehr @Shivansh2407

**Comment by Shivansh2407** [comment]
Yes @AdityaTeltia , You can go ahead and make a PR

**Comment by AdityaTeltia** [comment]
Sure , I tried this in inspect elements let me do this in code and i will make the pr .

**Comment by AdityaTeltia** [comment]
Can you tell how to setup the environment I have downloaded ruby but when  I write 
```gem install bundler```
it says gem not found ?
I am unable to find how to set it up ?
@Shivansh2407 @danielluehr

**Comment by anushri20** [comment]
Hi @Shivansh2407 , there is a PR opened for this issue.

**Comment by AABHINAAV** [comment]
hello, @Shivansh2407 , I can capable of solving these issues easily. 
please tell me if this is still open to work on ?
and how can i get into some guidance or organisational community channel ?

**Comment by manjotsidhu** [comment]
Kindly close, fixed in #528
