### ISSUE TITLE
Dark mode changes after refreshing the page

### ISSUE THREAD

**Issue by deepak2431** [CircuitVerse/Interactive-Book#48]
#### I am submitting a -
* [] **Bug Report**

#### Describe your bug/feature -
The dark mode change by default on refreshing the page.

**Comment by ShreyaPrasad1209** [comment]
**Duplicate Issue**
This issue is already open at #12 .

**Comment by deepak2431** [comment]
@ShreyaPrasad1209 Thanks for the review. I will close it.
