### ISSUE TITLE
Correction in the truth table

### ISSUE THREAD

**Issue by rishabhgit0608** [CircuitVerse/Interactive-Book#481]
2nd truth table under the boolean functions tab needs a correction
https://learn.circuitverse.org/docs/bool2.html
![Screenshot (217)](https://user-images.githubusercontent.com/53399949/97348828-b7194a80-18b4-11eb-8612-f7ce5d8f7e53.png)

**Comment by rishabhgit0608** [comment]
@abhinavsri360 this issue is fixed and yes their is a PR associated with it and I tried fixing it.  https://github.com/CircuitVerse/Interactive-Book/pull/482 thank you

**Comment by Shivansh2407** [comment]
@rishabhgit0608 please redirect your PR to the GSOD2020 Branch as the Book currently is undergoing a lot of changes and we will be merging that to Master soon . Please let us know if you need any help 👍 .

**Comment by rishabhgit0608** [comment]
Shall I have to make a new PR for this ??

**Comment by rishabhgit0608** [comment]
@Shivansh2407 I made a PR to GSOD2020 Branch. thank you

**Comment by manjotsidhu** [comment]
Fixed by #460
