### ISSUE TITLE
Table Contents not Visible in Dark Mode [GSoD 2020 Branch]

### ISSUE THREAD

**Issue by Shivansh2407** [CircuitVerse/Interactive-Book#483]
## Describe the bug

The table contents in the new Interactive Book ( GSoD 2020 Branch ) are only visible in light mode. While changing to Dark Mode the contents vanish away and only an empty table is visible.
Please find the screenshots attached below

## To Reproduce

1.  Go to 'betalearn.circuitverse.org'
2.  Click on 'Any Page Containig Table'
3.  Click on 'Dark Mode'
4.  See error

## Expected behavior

The table should show contents even in dark mode.

## Screenshots

Light Mode:
![image](https://user-images.githubusercontent.com/42182955/97441293-9271b100-194e-11eb-9168-8ed7a7299aeb.png)

Dark Mode:
![image](https://user-images.githubusercontent.com/42182955/97441241-8259d180-194e-11eb-8f78-85b0cab76bf5.png)

## Desktop (please complete the following information):

* OS: [Windows]
* Browser [Chrome]

## Additional context

Please make PRs on GSOD-2020 Branch

**Comment by anushri20** [comment]
@Shivansh2407 Can I work on this?

**Comment by anushri20** [comment]
@Shivansh2407 Hi, I would like to work on this?

**Comment by Shivansh2407** [comment]
Yeah @anushri20 go ahead and make a PR👍

**Comment by ayushontop** [comment]
working on this

**Comment by Shivansh2407** [comment]
@ayushontop , actually we are discussing currently to remove the dark mode, so I suggest you to please pick other issues to fix. @satu0king Please let me know your views on removing the dark mode.

**Comment by ayushontop** [comment]
@Shivansh2407 ohk thanks

**Comment by anushri20** [comment]
@Shivansh2407 I have made the PR by the way.

**Comment by Vishal-raj-1** [comment]
![xor](https://user-images.githubusercontent.com/59874304/104122333-8355a900-536a-11eb-861c-e4d6676c549a.JPG)

@Shivansh2407 I think this issue is solved you can close this issue now!!

**Comment by manjotsidhu** [comment]
@Shivansh2407 kindly close, fixed in #528
