### ISSUE TITLE
To add some more new Features

### ISSUE THREAD

**Issue by saumyasrivastava08** [CircuitVerse/Interactive-Book#491]
I was thinking we should add on more features for practicing the questions. Such as MCQ's, Short and long questions some Mock test Papers too. 
Most of the colleges take MCQ's test students can practice here.
Adding a mock test feature will lead to enthusiasm among students to practice more.

**Comment by 2019UCP1350** [comment]
I think it is a very good features
Can I work on this?

**Comment by ayan-biswas0412** [comment]
@ritik307 and @Samridhi-98 can you reference your PRs here #505

**Comment by ritik307** [comment]
@ayan-biswas0412  just did that....plz look into it

**Comment by ayan-biswas0412** [comment]
Thanks @ritik307

**Comment by ayan-biswas0412** [comment]
@saumyasrivastava08 can you close this issue ? Ref #505

**Comment by Samridhi-98** [comment]
@ayan-biswas0412  Done!

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412 Done!

Thanks @Samridhi-98

**Comment by ayan-biswas0412** [comment]
@Samridhi-98 @ritik307 you can close your old PRs which got immense merge conflict before

**Comment by Samridhi-98** [comment]
@ayan-biswas0412  Already done.

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412 Already done.

```Fixes #505``` change in your PR message

**Comment by ritik307** [comment]
@ayan-biswas0412 Done! plz look into it and let me know of any further changes.

**Comment by Samridhi-98** [comment]
> > @ayan-biswas0412 Already done.
> 
> `Fixes #505` change in your PR message

Done

**Comment by ayan-biswas0412** [comment]
@ritik307 and @Samridhi-98 now it looks fine 🥰

**Comment by manjotsidhu** [comment]
Superseded by #505
