### ISSUE TITLE
Canonical Functions Page not rendering properly [GSOD 2020 Branch]

### ISSUE THREAD

**Issue by Shivansh2407** [CircuitVerse/Interactive-Book#494]
## Describe the bug
There are some white spaces which needs to be cleared so that it gets rendered properly similar to other pages .

## To Reproduce

1.  Go to '/docs/logic-design/canonical.html'
2.  See error

## Screenshots

![image](https://user-images.githubusercontent.com/42182955/104173371-adbb6b00-542b-11eb-9a5c-6bf8ae24a4f5.png)

## Desktop (please complete the following information):

* OS: [Windows]
* Browser [Chrome]

## Additional context

Comment Below to Claim the Issue!

**Comment by anushri20** [comment]
@Shivansh2407 Hi, I would like to work on this.

**Comment by Shivansh2407** [comment]
@anushri20 you can go ahead and make a PR. Happy Contributing 🎉

**Comment by Shivansh2407** [comment]
#497 Merged
