### ISSUE TITLE
Close menu item when clicking on another menu element [ GSOD 2020 Branch ]

### ISSUE THREAD

**Issue by Shivansh2407** [CircuitVerse/Interactive-Book#495]
## Is your feature request related to a problem? Please describe.

The Idea is to make a Clean Sidebar which closes menu item whenever another menu element is clicked. This way, all the menu items will not be left opened, and will help the user to navigate through the items easily.

## Additional context

Comment below to Claim the Issue!

**Comment by Zeeshan-2k1** [comment]
I would like to work upon it.

**Comment by Shivansh2407** [comment]
@Zeeshan-2k1 you can go ahead and make a PR. Happy Contributing 🎉

**Comment by chinmaym07** [comment]
Hey @Shivansh2407 Can I try this issue .? if it's available .?

**Comment by Shivansh2407** [comment]
Go ahead @chinmaym07 as @Zeeshan-2k1 has not raised any PR for this issue . Keep Contributing 🎉

**Comment by 2019UCP1350** [comment]
@Shivansh2407 
On the same circuit page, the magnifier icons on the bottom right corner are hiding the text behind it and the cancel button to return to normal view from fullscreen view looks like an image rather than a clickable button.
I had properly described this formatting issue in #498 
So, Can I work on it?

**Comment by Shivansh2407** [comment]
@2019UCP1350 Please attach screenshots to support your statement . Here specifically I am referring to the Sidebar in the Book ( GSOD-2020 Branch ). When an item in the sidebar is clicked, and if any other item/dropdown in the sidebar is open, then it should get closed automatically on clicking another item. Reference Link - https://jqueryui.com/accordion/

**Comment by Shivansh2407** [comment]
@chinmaym07 are you working on this issue?

**Comment by chinmaym07** [comment]
> @chinmaym07 are you working on this issue?

Yes @Shivansh2407 ..will try make a pr asap.sorry for the delay.

**Comment by 2019UCP1350** [comment]
@Shivansh2407 

There is the screenshot of the issues I was talking about in #498.

As mentioned in the screenshot, the main button isn't working and the magnifier icons are hiding the text. Along with that, the cancel icon doesn't look like a button so we can add some CSS to this icon to make it appear more like a button.

![Screenshot (360)_LI](https://user-images.githubusercontent.com/59130222/107115572-92f5de00-6893-11eb-8c66-c3d56c9c2204.jpg)

Can I work on this?

**Comment by chinmaym07** [comment]
@Shivansh2407 Can we make the sidebar closed by default . as whenever I click on a link .It will redirect to a new page which will by default has the sidebar opened .so if I try to close on clicking a link it will again be opened when the new page is rendered completely.!!
![Peek 2021-02-10 15-20](https://user-images.githubusercontent.com/44670961/107493505-b2eb1180-6bb3-11eb-82c5-c2e43c361e6d.gif)
If we close it by default .then It will go like this .
![Peek 2021-02-10 15-34](https://user-images.githubusercontent.com/44670961/107495045-9354e880-6bb5-11eb-9d2f-3168e0cd46ec.gif)

Please give your inputs on this.

**Comment by Shivansh2407** [comment]
> 
> 
> @Shivansh2407 Can we make the sidebar closed by default . as whenever I click on a link .It will redirect to a new page which will by default has the sidebar opened .so if I try to close on clicking a link it will again be opened when the new page is rendered completely.!!
> ![Peek 2021-02-10 15-20](https://user-images.githubusercontent.com/44670961/107493505-b2eb1180-6bb3-11eb-82c5-c2e43c361e6d.gif)
> If we close it by default .then It will go like this .
> ![Peek 2021-02-10 15-34](https://user-images.githubusercontent.com/44670961/107495045-9354e880-6bb5-11eb-9d2f-3168e0cd46ec.gif)
> 
> @Shivansh2407 If possible Please give your inputs on this.

Please take a look at the GSOD 2020 Branch, It has an updated sidebar for which this issue is created.

**Comment by 2019UCP1350** [comment]
> @Shivansh2407
> 
> There is the screenshot of the issues I was talking about in #498.
> 
> As mentioned in the screenshot, the main button isn't working and the magnifier icons are hiding the text. Along with that, the cancel icon doesn't look like a button so we can add some CSS to this icon to make it appear more like a button.
> 
> ![Screenshot (360)_LI](https://user-images.githubusercontent.com/59130222/107115572-92f5de00-6893-11eb-8c66-c3d56c9c2204.jpg)
> 

@Shivansh2407   Can I work on this?

**Comment by manjotsidhu** [comment]
@Shivansh2407 we can close this issue as #513 merged

**Comment by Shivansh2407** [comment]
Closing this Issue, Fixed in #513
