### ISSUE TITLE
Fix Interactive Element Alignment [GSOD 2020 Branch ]

### ISSUE THREAD

**Issue by Shivansh2407** [CircuitVerse/Interactive-Book#496]
## Describe the bug

The Interactive element Outputs an unordered list when the user provides an integer input. The List alignment is not proper and needs to be fixed.

## To Reproduce

1.  Go to '/docs/binary-representation/encoding-information.html'
2.  Click on 'Send' after providing an input
3.  See error

## Expected behavior

The Alignment needs to be fixed.

## Screenshots

![image](https://user-images.githubusercontent.com/42182955/104179640-2e7d6580-5432-11eb-8380-a357ef1ac687.png)

## Desktop (please complete the following information):

* OS: [Windows 10]
* Browser [Chrome]

## Additional context

Comment Below to Claim the Issue!

**Comment by Vishal-raj-1** [comment]
I am looking forward to this issue !!

**Comment by Shivansh2407** [comment]
@Vishal-raj-1 you can go ahead and make a PR. Happy Contributing 🎉

**Comment by anushri20** [comment]
@Shivansh2407 Hi, Can i work on this?

**Comment by Vishal-raj-1** [comment]
@anushri20 Yes !!

**Comment by Shivansh2407** [comment]
#500 Merged
