### ISSUE TITLE
Fix the clickable event of the main button  and some overlapping elements in the circuit diagram.

### ISSUE THREAD

**Issue by 2019UCP1350** [CircuitVerse/Interactive-Book#498]
## Describe the bug

The main button on the NAND gate method page isn't working; the magnifier icons on the bottom right corner are hiding the text behind it and the cancel button to return to normal view from fullscreen view looks like an image rather than a clickable button.

## To Reproduce

1.  Go to 'https://learn.circuitverse.org/docs/nand_gate_method.html'
2.  Scroll down to the bottom.
3. .  Click on the main button on the circuit diagram.

## Expected behavior

On clicking the button, the circuit toolbar should open. 

The magnifier icons must be adjusted so that they don't cover the text behind them.

The cancel button to return to normal view from fullscreen view must look like a clickable button rather than an image.

## Screenshots

In the above screenshot. you can see the main button isn't working.
Moreover, the magnifying icons are hiding the text.

![bug](https://user-images.githubusercontent.com/59130222/105812178-b2f3ea80-5fd3-11eb-936a-f84b54ba6b1c.png)

in the above screenshot, you can see the cancel button looks more like an image.

![bug 1](https://user-images.githubusercontent.com/59130222/105812495-4af1d400-5fd4-11eb-8f4a-be964083ce65.png)

Faced the above issue on the pc with the following specification.

* OS: [Windows]
* Browser [Edge]
* Version [88.0.705.50 ]

**Comment by 2019UCP1350** [comment]
I would like to work on this issue. Could I work on it?

**Comment by Shivansh2407** [comment]
@2019UCP1350 , You can refer to the GSOD 2020 Branch for the transformed Interactive Book, we have some open issues for the same. After fixing them, we will be merging it soon to the master.

**Comment by 2019UCP1350** [comment]
@Shivansh2407 in GSOD 2020 Branch only the clickable button issues are mentioned. Formatting issues are still not mentioned yet.
So, can I work on them?
