### ISSUE TITLE
Request for Issue templates

### ISSUE THREAD

**Issue by sal2701** [CircuitVerse/Interactive-Book#5]
#### Is your feature request related to a problem? Please describe.
Templates for users to fill in while submitting issues will be helpful.

#### Describe the solution you'd like
Issue templates for Bug Report, Feature Request while raising an issue are necessary and will help maintain uniformity

#### Are you working on this? (Yes/No)
No

**Comment by ankitkataria** [comment]
We can refer the [this](https://github.com/CircuitVerse/CircuitVerse/tree/master/.github) for the templates.

**Comment by Parikshit-Hooda** [comment]
@ankitkataria We should have templates for this repo as well.

**Comment by coding-CEO** [comment]
@YashKumarVerma I think this issue can be closed.
We have templates for bug report and feature requests.
