### ISSUE TITLE
Edit on github redirects to index.md page

### ISSUE THREAD

**Issue by deepak2431** [CircuitVerse/Interactive-Book#51]
#### I am submitting a -
* [] **Bug Report**

#### Describe your bug/feature - 
The edit link on the page redirects to the index.md page.

#### Current behaviour - 
The Edit on Github link on the page redirects to the index page.

#### Steps to reproduce the behaviour-
1. Open the interactive-book.
2. Click on the Edit on Github link you will be redirected to the index.md page.

#### Expected behaviour -
The edit link present on the page should redirect to the main github repository of the Interactive-Book.

**Comment by ShreyaPrasad1209** [comment]
**Duplicate Issue**
This issue is already open at https://github.com/CircuitVerse/CircuitVerseDocs/issues/155

**Comment by deepak2431** [comment]
@ShreyaPrasad1209 Thanks for reviewing. I will close this issue.
