### ISSUE TITLE
[GSoD2020 Branch] Dark Mode Button broken on Home Page

### ISSUE THREAD

**Issue by manjotsidhu** [CircuitVerse/Interactive-Book#514]
## Describe the bug
"Dark Mode" is broken on Home Page in GSoD2020 branch, fixing this is a priority.

## To Reproduce

Steps to reproduce the behavior -
1.  Go to 'https://betalearn.circuitverse.org'
2.  Click on 'Dark mode'.

## Expected behavior
Dark Mode switch should work as intended, it should change the color scheme to Dark.

**NOTE**: This Dark Mode switch mode just works fine on other pages.

## Desktop:

* OS: Windows 10 Pro 20H2
* Browser: Google Chrome
* Version: 85

---
If anyone would like to work on this, please make sure you are active enough to fix this ASAP.

**Comment by infern018** [comment]
can u assign this to me? @manjotsidhu

**Comment by manjotsidhu** [comment]
> can u assign this to me? @manjotsidhu

Go ahead

**Comment by infern018** [comment]
I had a small doubt here @manjotsidhu  for accessing the URL u mentioned in my local system what steps I have to take? As the one visible at http://127.0.0.1:4000// is showing that dark mode is working fine

**Comment by manjotsidhu** [comment]
> I had a small doubt here @manjotsidhu for accessing the URL u mentioned in my local system what steps I have to take? As the one visible at http://127.0.0.1:4000// is showing that dark mode is working fine

It's the same, make sure you are on `GSoD2020` branch

**Comment by infern018** [comment]
![image](https://user-images.githubusercontent.com/52378712/108826735-aff81400-75ea-11eb-945f-d9cae1e2b50d.png)
I am getting this error while running bundle for GSoD2020 branch

**Comment by manjotsidhu** [comment]
> ![image](https://user-images.githubusercontent.com/52378712/108826735-aff81400-75ea-11eb-945f-d9cae1e2b50d.png)
> I am getting this error while running bundle for GSoD2020 branch

Did you tried `bundle install` ?

**Comment by infern018** [comment]
> > ![image](https://user-images.githubusercontent.com/52378712/108826735-aff81400-75ea-11eb-945f-d9cae1e2b50d.png)
> > I am getting this error while running bundle for GSoD2020 branch
> 
> Did you tried `bundle install` ?

yes I did that even then I am getting this error

**Comment by infern018** [comment]
Is there any file **./color_schemes/circuitverse** in the GSoD branch?

**Comment by manjotsidhu** [comment]
> Is there any file **./color_schemes/circuitverse** in the GSoD branch?

Yes, it's under `_sass` directory

**Comment by infern018** [comment]
One doubt why in my error it saying that _error converting 'assets/css/just-the-docs-default.scss'_ when there is no such file _just-the-docs-default.scss_ ?

**Comment by manjotsidhu** [comment]
> One doubt why in my error it saying that _error converting 'assets/css/just-the-docs-default.scss'_ when there is no such file _just-the-docs-default.scss_ ?

We use just-the-docs gem, it has its assets. It's trying to find that.

**Comment by infern018** [comment]
Hey @manjotsidhu  sorry to bother you again but I successfully resolved the setup conflicts, I am stuck at one part that the code in _includes/general_scripts.html_ is being executed every time except when we are on the homepage, can you guide me how will I know if we are on the homepage?

**Comment by manjotsidhu** [comment]
@Shivansh2407 Closing since #523 merged. Thanks @infern018.
