### ISSUE TITLE
dark mode UI enhancements

### ISSUE THREAD

**Issue by JoshuaPoddoku** [CircuitVerse/Interactive-Book#52]
## Feature: UI enhancements (including color and fonts)

![Screenshot (39)](https://user-images.githubusercontent.com/31725457/68398683-20cbb080-019b-11ea-8237-9c3ef1ae61fd.png)
-  Color transition in Subheading and Paragraph for better UX.
- Suggested font-family: Roboto-mono, monospace for paragraphs.
- Color for links: #00e8b3 
- Color for background: #13101f
- Color for paragraph:  #efc7ff 

![Screenshot (38)](https://user-images.githubusercontent.com/31725457/68398684-21644700-019b-11ea-9534-2e2c782d8d98.png)

- links in the anchor tags need to be enhanced.
- Panel and Table color transition with darker background makes it look good.
- Overall UI can use material bootstrap

![Screenshot (41)](https://user-images.githubusercontent.com/31725457/68400878-c3396300-019e-11ea-9b11-e2700c22046d.png)
- A quick comparison of Ui with the present one.

## References:
- Fonts: [Roboto-Mono](https://fonts.google.com/?selection.family=Roboto+Mono)
  -  Add in Html: `<link href="https://fonts.googleapis.com/css?family=Roboto+Mono&display=swap" rel="stylesheet">`
  - Specify in CSS: `font-family: 'Roboto Mono', monospace;`
- Checkout Dark themes: https://material.io/design/color/dark-theme.html
- Material Design Bootstrap: https://mdbootstrap.com/docs/jquery/components/demo/

**Comment by JoshuaPoddoku** [comment]
This can be an issue for GCI students.

**Comment by aayush-05** [comment]
@tachyons can be closed now
