### ISSUE TITLE
Sign up with other social media

### ISSUE THREAD

**Issue by dev9414** [CircuitVerse/Interactive-Book#53]
I am submitting
Feature request
We can also add feature like
Sign up with:LinkedIn,GitHub

Right now there is only 4 option available
![Screenshot_20191107-230025~2](https://user-images.githubusercontent.com/46513305/68412752-ce968980-01b2-11ea-88fc-e87ca8e48fdc.png)

**Comment by satu0king** [comment]
Discus is a 3rd party plugin, we cannot change the login methods for them :)
