### ISSUE TITLE
some links ->broken -> readme.md

### ISSUE THREAD

**Issue by pavanjoshi914** [CircuitVerse/Interactive-Book#533]
## Describe the bug
  found two links broken in readme.md
## A clear and concise description of what the bug is.
link for cv logo and git-contributing to project is broken
## To Reproduce

1.  Go to 'https://github.com/CircuitVerse/Interactive-Book'
2.  visit readme.md
4.  See error

## Screenshots
link broken for cv logo :: https://github.com/CircuitVerse/CircuitVerse/raw/master/public/img/cvlogo.svg?sanitize=true
![2021-03-14_06-43](https://user-images.githubusercontent.com/55848322/111054430-ae579880-8492-11eb-8bb9-3a1fc7b18ff5.png)

link broken for git-project contribution guidline::http://git-scm.com/book/ch5-2.html

![2021-03-14_06-47](https://user-images.githubusercontent.com/55848322/111054439-bdd6e180-8492-11eb-9732-510650a6b19e.png)

third link in image seems little bit outdated and website is not secure with https
![2021-03-14_06-51](https://user-images.githubusercontent.com/55848322/111054442-c0393b80-8492-11eb-81ef-1e8fc144e79a.png)

**Comment by pavanjoshi914** [comment]
@tachyons any inputs here?

**Comment by prabhat04011998** [comment]
hey @pavanjoshi914 i wanna take this issue,
if yes where I'll get the  correct links?

**Comment by pavanjoshi914** [comment]
> hey @pavanjoshi914 i wanna take this issue,
> if yes where I'll get the correct links?

Hii @prabhat04011998 already working on it . thanks

**Comment by prabhat04011998** [comment]
okay no worries! Thanks

**Comment by manjotsidhu** [comment]
@pavanjoshi914 1. You can use the updated logo (https://raw.githubusercontent.com/CircuitVerse/CircuitVerse/master/simulator/src/img/cvlogo.svg?sanitize=true) to fix this
2. Git - Contributing to a Project Link is working fine
3. For the time being, you can update to https URL of the same blog post, https://who-t.blogspot.com/2009/12/on-commit-messages.html

Also, please do make Pull Request on `GSoD2020` branch. Thanks!

**Comment by Shivansh2407** [comment]
> 
> 
> @pavanjoshi914
> 
>     1. You can use this [updated logo](https://raw.githubusercontent.com/CircuitVerse/CircuitVerse/master/simulator/src/img/cvlogo.svg?sanitize=true). [✅ Done by @Shivansh2407].
> 
>     2. Git - Contributing to a Project Link is working fine for me. [☑️ Not an issue]
> 
>     3. For the time being, you can update to https URL of the same blog post, https://who-t.blogspot.com/2009/12/on-commit-messages.html.
> 
> 
> Also, please do make Pull Request on `GSoD2020` branch. Thanks!

@pavanjoshi914 You can just make a PR with the updated Links. I have updated the Logo! Keep Contributing 🎉

**Comment by two-ticks** [comment]
![image](https://user-images.githubusercontent.com/68433541/112719309-569f3f80-8f1e-11eb-9817-4e026177f8e8.png)
[https://github.com/CircuitVerse/Interactive-Book/blob/GSoD2020/assets/images/ib.png](https://github.com/CircuitVerse/Interactive-Book/blob/GSoD2020/assets/images/ib.png) link is also broken in the README.md

**Comment by manjotsidhu** [comment]
Fixed by #460
