### ISSUE TITLE
broken links and blur images in recommendation 

### ISSUE THREAD

**Issue by two-ticks** [CircuitVerse/Interactive-Book#540]
## Describe the bug

Images are blurry and image for `binary numbers` is not loading

## To Reproduce

1.  Go to 'https://learn.circuitverse.org/'
2.  Scroll down to 'ALSO ON INTERACTIVE BOOK' section
3.  See error

## Expected behavior

Images should load and must be of standard quality 

## Screenshots

![image](https://user-images.githubusercontent.com/68433541/112846902-28f3fb00-90c4-11eb-9039-ee2eb2a45513.png)

I would like to work on it

**Comment by manjotsidhu** [comment]
There might be several pages where a post doesn't contain a single image, due to which Disqus recommendations don't show any image. For those posts, we can add specific meta tag to load a custom image. We need to design a default fallback image to be able to be used by this meta tag.
```<meta property="og:image" content="IMAGE_URL">```

**Comment by Shivansh2407** [comment]
Hey @manjotsidhu, these links are currently broken as they're mapped to the previous book. Could you please look into this as these related with Disqus. Thanks! :+1:
