### ISSUE TITLE
Elaborate Flip Flop Interaction explanation

### ISSUE THREAD

**Issue by ShreyaPrasad1209** [CircuitVerse/Interactive-Book#55]
**Current Status**
https://learn.circuitverse.org/docs/flipflop2.html contains an interactive exercise on flip flops and explanation about state tables. This can be further elaborated so that a beginner can understand it.

**Changes required**
Improve explanation such that understanding of interactive flip flop increases.

**Are you working on this issue?**
No, for GCI participants under difficult

**Comment by mohit-003** [comment]
What should we do the the explanation on the flip flop interactions https://learn.circuitverse.org/docs/flipflop2.html or the flip flop https://learn.circuitverse.org/docs/flipflop

**Comment by sakshi1499** [comment]
Explanation on the flip flop interactions has to be focused @mohit-003
