### ISSUE TITLE
Broken Links in Sequential MSI -> Registers

### ISSUE THREAD

**Issue by Shivansh2407** [CircuitVerse/Interactive-Book#551]
## Describe the bug

The links present under the sub-modules heading, are broken and lead to a '404' page not found!

## To Reproduce

1.  Go to 'https://learn.circuitverse.org/docs/seq-msi/registers.html#sub-modules'
2.  Click on Any of the 4 links present under the Sub-Modules Heading
3.  See error

## Expected behavior

It should take us directly to the linked sub-module.

## Additional Context

Anybody willing to work on this issue please comment below. Happy Contributing :tada:

**Comment by himanshu007-creator** [comment]
Hi, i would like to work on this issue 😄

**Comment by Shivansh2407** [comment]
> Hi, i would like to work on this issue smile

Hey @himanshu007-creator, Daniel has taken up this issue and also has raised a PR. I'll suggest you to look for other issues, and we'll be opening some issues soon as well! :+1:  Thank you for your interest
Keep Contributing :tada:
