### ISSUE TITLE
Improve Copyright Font Color

### ISSUE THREAD

**Issue by ShreyaPrasad1209** [CircuitVerse/Interactive-Book#553]
## Describe the bug
At the end of every page, the copyright line seems hard to read in dark mode. 

## To Reproduce

1.  Go to https://learn.circuitverse.org/
2.  Scroll down to footer
4.  See the error

## Expected behavior
It should be easily readable in dark mode. It will be great if font color is changed to grey or something similar to make it easily readable.

## Screenshots
![image](https://user-images.githubusercontent.com/43600306/120886398-5cdf2580-c60b-11eb-8669-94fab887de45.png)

## Desktop (please complete the following information):

* OS: Windows 10
* Browser: Google Chrome

## Are you working on this bug?

No I'm creating this for Open Source Day participants and is not open for contributors.

**Comment by astelrastogi** [comment]
I want to work on this issue

**Comment by marshalmiller** [comment]
I can also work on this issue.

**Comment by vvijayalakshmi21** [comment]
I wanna join the queue if still available

**Comment by Shivansh2407** [comment]
As @marshalmiller is working on a PR currently for #505, so you can go ahead @vvijayalakshmi21 :+1:

**Comment by vvijayalakshmi21** [comment]
Thanks. Please can you help me locate the find that needs changing?
I am a newbie to Ruby and would appreciate some pointers.

**Comment by vvijayalakshmi21** [comment]
An Inspect using Chrome shows that the element needs changing is:
<p class="text-small text-grey-dk-100 mb-0">Copyright © 2021 Contributors to CircuitVerse. Distributed under a [CC-by-sa] license.</p>

**Comment by vvijayalakshmi21** [comment]
Under docs folder I see
![image](https://user-images.githubusercontent.com/34595292/125826333-aa7af909-4100-4b5e-b3d4-2d52785737d9.png)
which I assume corresponds to
![image](https://user-images.githubusercontent.com/34595292/125826367-8a5be3cf-7604-4385-a59a-78235a395840.png)
But I dont know where the Home link related stuffs are located

**Comment by Shivansh2407** [comment]
> An Inspect using Chrome shows that the element needs changing is:
> 
> Copyright © 2021 Contributors to CircuitVerse. Distributed under a [CC-by-sa] license.

Tip :star: : You can find these in VSCode Search! If not do let us know, I'll help you out.

**Comment by vvijayalakshmi21** [comment]
I see on _config.yml
`footer_content: "Copyright &copy; 2021 Contributors to CircuitVerse. Distributed under a [CC-by-sa] license."
` 
But not the html where this needs to be changed

**Comment by vvijayalakshmi21** [comment]
`<p class="text-small text-grey-dk-100 mb-0">`
I presume the text-grey here needs to be changed. But I cannot locate the html/css file that contains it.

**Comment by vvijayalakshmi21** [comment]
@Shivansh2407 please can you help here?

**Comment by astelrastogi** [comment]
> As @marshalmiller is working on a PR currently for #505, so you can go ahead @vvijayalakshmi21 👍
im also working on this issue

**Comment by vvijayalakshmi21** [comment]
I see that _sass\color_schemes does have a dark mode file.
Should I add $text-color and give it a value?

**Comment by Shivansh2407** [comment]
Sure! Please test it out on your machine and post a screenshot of the fix when you raise a PR. Thanks

**Comment by vvijayalakshmi21** [comment]
Hello,
As per my analysis, this repo uses Just the Docs documentation theme which by default has the below:
`{%- if site.footer_content -%}
<p class="text-small text-grey-dk-100 mb-0">{{ site.footer_content }}</p>
{%- endif -%}`

And our _config.yml does have a footer_content set.
This indicates that by default the class text-grey-dk-100 will be applied for this custom footer

I am not sure how to customize this without changing the Just the Docs repo.
Please suggest @ShreyaPrasad1209

**Comment by AsherThomasBabu** [comment]
> I am not sure how to customize this without changing the Just the Docs repo.

@vvijayalakshmi21 just-the-docs-themes' css files are locally available in the repo, you can find them at  `/Interactive-Book/_site/assets/css`

You should be done by just changing the `text-grey-dk-100` color property in the `just-the-docs-circuitversedark.css` file.

Also Since OSD was on the 15th, I suppose these issues tagged as **good first** can now be taken on by other contributors as well?
@ShreyaPrasad1209 or the other Mentors, please confirm.

**Comment by vvijayalakshmi21** [comment]
@AsherThomasBabu Thanks for your pointer. I see only the below in just-the-docs-circuitversedark.css file.
![image](https://user-images.githubusercontent.com/34595292/126061034-3e33d84e-3824-4dd0-8e5f-684cf0c7bda0.png)
Do you mean to say I can just set up the value of `text-grey-dk-100` in this file to a lighter shade and it will be picked up?

**Comment by AsherThomasBabu** [comment]
> Do you mean to say I can just set up the value of `text-grey-dk-100` in this file to a lighter shade and it will be picked up?

Yup @vvijayalakshmi21 you could add that to the end of the file, while making sure to add a `!important` rule so that it gets the priority over the default color.

**Comment by Vedanshi-Shah** [comment]
Can I work on this issue? Is it open for contributions?

**Comment by ShreyaPrasad1209** [comment]
@Vedanshi-Shah sure

**Comment by amruta-11** [comment]
can I work on this issue?

**Comment by Palaksharma23** [comment]
Can i work on this issue ?

**Comment by Palaksharma23** [comment]
i have solved this issue , i will make a pr soon
