### ISSUE TITLE
Boolean Algebra Interactive Element Not Working Properly

### ISSUE THREAD

**Issue by Shivansh2407** [CircuitVerse/Interactive-Book#556]
## Describe the bug

Regardless of the Dark/ Light Mode, the Interactive Element i.e. the switches and the Gates Drop-down do not appear and the place is blank. When the user clicks on the Blank space, the switch appears along with the drop-down and the other switch does not appears. 

## To Reproduce

1.  Go to 'https://learn.circuitverse.org/docs/binary-algebra/boolean-algebra.html'
2.  Scroll down to 'https://learn.circuitverse.org/docs/binary-algebra/boolean-algebra.html#click-on-gate-to-toggle-between-other-gates'
3.  See error

## Expected behavior

It should be visible completely when the page loads and should not remain blank.

## Screenshots

Looks Blank when the page the page loads:
![Screenshot from 2021-06-25 17-37-02](https://user-images.githubusercontent.com/42182955/123423376-1d3da500-d5dd-11eb-84d8-0358e8996949.png)

On first click on the blank space:
![Screenshot from 2021-06-25 17-43-18](https://user-images.githubusercontent.com/42182955/123423372-1c0c7800-d5dd-11eb-99bf-6be2c179d520.png)

On second click on the second blank space:
![Screenshot from 2021-06-25 17-43-23](https://user-images.githubusercontent.com/42182955/123423360-1878f100-d5dd-11eb-8e3f-89bcf86f0790.png)

## Desktop (please complete the following information):

* OS: [Ubuntu 20.04.2]
* Browser [Firefox Web Browser]

## Additional context

This issue is reserved for Open Source Day participants.

**Comment by Ayush7614** [comment]
I have work on this issue @Shivansh2407 please assign  me

**Comment by LinaJohnson** [comment]
I'm an OSD participant. If this is still available, can I assign this one to myself?

**Comment by padmajabhol** [comment]
Want to on this.

**Comment by Palaksharma23** [comment]
@Ayush7614 if you have already fixed the issue , you can raise a pull request

**Comment by Palaksharma23** [comment]
I am giving a try to this issue.
