### ISSUE TITLE
Convert all HTML image tags to Jekyll style include

### ISSUE THREAD

**Issue by manjotsidhu** [CircuitVerse/Interactive-Book#558]
Convert all HTML tags to the recommended liquid syntaxes :

https://learn.circuitverse.org/contributing_guidelines.html#figure-examples

**Comment by Amishakumari544** [comment]
I am working on this.

**Comment by Amishakumari544** [comment]
I am working on this.

**Comment by Amishakumari544** [comment]
I am facing problem while installing ruby on windows can anyone help?

**Comment by Amishakumari544** [comment]
I am facing issue while installing ruby on windows can anyone help me?
