### ISSUE TITLE
Add POS and SOP 

### ISSUE THREAD

**Issue by ShreyaPrasad1209** [CircuitVerse/Interactive-Book#56]
Add following topics after Boolean function-
1. Sum of Product
2. Product of Sum
3. Minimal to Canonical Form Conversion 

Explain with examples, diagrams, flow-charts etc.
 
You are expected to extend the content from here - https://learn.circuitverse.org/docs/bool2.html#sum-of-product-expressions-sop

**Comment by ShubhankarKG** [comment]
This is a good one open here. I can work on this. Please confirm @YashKumarVerma @Shivansh2407
