### ISSUE TITLE
feat: preserve sidebar collapse state

### ISSUE THREAD

**Issue by vedant-jain03** [CircuitVerse/Interactive-Book#565]
## Describe the bug

- Sidebar loses the previous state after rendering the page and also after jumping to next page it is mainly due to it does not have global state like dark/light mode.

## To Reproduce

1.  Go to 'https://learn.circuitverse.org/'
2.  Click on 'sidebar'
3.  Click on 'next'
4.  See error

## Expected behavior

After clicking next sidebar should be in previous state.

## Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

## Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Comment by vedant-jain03** [comment]
@tachyons @Shivansh2407

**Comment by vedant-jain03** [comment]
@nitin10s Please review 
We can shift sidebar button in main nav to have global state?

**Comment by nitin10s** [comment]
1. We can have the sidebar on the left on search bar in main nav, yes
2. We can remove Next and Previous buttons from the top and keep them just at bottoms. All pages have these buttons at the bottom except the Home page.
3. As of now, the sidebar button doesn't have different states for Enabled/Disabled, we can also add that for better feedback.

**Comment by vedant-jain03** [comment]
> 1. We can have the sidebar on the left on search bar in main nav, yes
> 2. We can remove Next and Previous buttons from the top and keep them just at bottoms. All pages have these buttons at the bottom except the Home page.
> 3. As of now, the sidebar button doesn't have different states for Enabled/Disabled, we can also add that for better feedback.

Can I go ahead with this?

**Comment by vedant-jain03** [comment]
For the 3 point, I can implement the functionality as documentation page have?

**Comment by vedant-jain03** [comment]
> 1. We can have the sidebar on the left on search bar in main nav, yes
> 2. We can remove Next and Previous buttons from the top and keep them just at bottoms. All pages have these buttons at the bottom except the Home page.
> 3. As of now, the sidebar button doesn't have different states for Enabled/Disabled, we can also add that for better feedback.

Actually @nitin10s I just realise that next_prev buttons are on top as well as on bottom for everypage and for home page it is just at top? If you allow me , I can just make it on bottom only for every page?

**Comment by manjotsidhu** [comment]
> @nitin10s Please review We can shift sidebar button in main nav to have global state?

Well that will have no change in the implementation whatsoever. Actually, the fix to this issue don't need to touch any UI side of things.

The toggle state of the button needs to be stored in local storage as a Boolean so that the browser recognizes the last saved state of the button. How we are going to do that ? The JS code for the button's onclick events are already mapped in global JS script and they are already in place to switch between Dark/Light mode. We just 1 line of code to store the state in local storage and 3 lines of code in init, to load the state after window is loaded.

**Comment by vedant-jain03** [comment]
@manjotsidhu actually sir. I have reviewed my work with nitin . He is working on the ui of where to place sidebar.

**Comment by vedant-jain03** [comment]
> He meant we need not change UI in any way to implement this, but we are changing it to simplify the top navigation we have in place. The correct way, even if one discussion leads to another is to open a new issue addressing the problem so that it can be taken up separately. Could you open a new issue: "Simplifying top navigation" and mention
> 
> 1. Removing Next and Previous buttons from the top and keep them just at bottoms.
> 2. Changing the position of sidebar to fit in the topmost level navigation.
> 
> Also, I've been quite busy with my office work. It'll take me some time before I could take up new designs, will keep you guys posted.

@nitin10s I have created issue for this, I will now raise a PR for global state without changing the UI of sidebar and after you are done with the UI part of this I will raise PR for that separately.
