### ISSUE TITLE
Back to Top Button

### ISSUE THREAD

**Issue by vedant-jain03** [CircuitVerse/Interactive-Book#567]
## Is your feature request related to a problem? Please describe.

As this is the documentation and have many y-direction pages, back-to-top button can allow users to go at the top of the document and see what they need.

## Describe the solution you'd like

I will try to implement fixed button that have sign '^' and using javascript I will try to give it functionality.

**Comment by Palaksharma23** [comment]
Are you currently working on this issue ?

**Comment by vedant-jain03** [comment]
Yes if mentors allowed me to do.

**Comment by vedant-jain03** [comment]
@nitin10s What do you think?
