### ISSUE TITLE
Scroll to top button not responsive

### ISSUE THREAD

**Issue by manjotsidhu** [CircuitVerse/Interactive-Book#569]
## Describe the bug

Recently implemented #568 is working well on Desktop, however it is not responsive to all screen widths. Specifically in mobile, the button goes out of the window.

## To Reproduce

1.  Go to 'https://learn.circuitverse.org'
2.  Scroll down sufficient enough 

## Expected behavior

Align the button to bottom right with same padding and make sure it is responsive.

## Screenshots

<img src="https://user-images.githubusercontent.com/22657113/136705978-6c183aad-2367-4210-b11d-5c18f9b3f868.png" width="300px" />

**Comment by vedant-jain03** [comment]
@manjotsidhu I want to go ahead with this issue.
