### ISSUE TITLE
"Comment" invisible in dark mode

### ISSUE THREAD

**Issue by ShreyaPrasad1209** [CircuitVerse/Interactive-Book#57]
**Problem**
Number of comments becomes invisible in dark mode  

**Solution**
`color: #E3E3E3`

**Screenshot**            
![2019-11-11 (8)](https://user-images.githubusercontent.com/43600306/68569979-82cf3300-0485-11ea-8f1b-a10657a90f08.png)

**Are you working on this issue**
No, for GCI participants under beginner-friendly

**Comment by GITHUBUSR01** [comment]
Done:
![Screen Shot 2019-12-22 at 11 02 50 AM](https://user-images.githubusercontent.com/42304949/71326067-a33dd480-24aa-11ea-8be5-12f1218828df.png)

**Comment by deepak2431** [comment]
@GITHUBUSR01 I can see on GCI dashboard that you have abandoned this task. Please claim the task and open a PR for it so that I can review your work.
Thanks!

**Comment by aayush-05** [comment]
@tachyons @nitin10s invalid issue, we can't access disqus internal files

**Comment by nitin10s** [comment]
@aayush-05 we need to something fo this, lots of issues with  Disqus :|

**Comment by manjotsidhu** [comment]
Fixed by #460
