### ISSUE TITLE
Not getting switch when selecting not gate 

### ISSUE THREAD

**Issue by Palaksharma23** [CircuitVerse/Interactive-Book#581]
## Describe the bug
On selecting not gate the switch disappears 

## To Reproduce
![image](https://user-images.githubusercontent.com/87171452/142752475-f661cea8-bb02-4aa1-a35c-136a98b2396e.png)

1.  Go to 'Binary Algebra'
2.  Click on 'Boolean Algebra'
3.  Scroll down to 'Click on gate to toggle between other gates'
4.  See error

## Expected behavior
It should also have switch just like other gates have

![image](https://user-images.githubusercontent.com/87171452/142752512-2cbabda7-b11e-4538-a657-b1e0e51393ad.png)

## Desktop (please complete the following information):

OS = Windows 10
Browser = Chrome 

## Are you working on this issue ?

Yes , i am working on this issue , will raise a pr soon .

**Comment by manjotsidhu** [comment]
Linked to #556
