### ISSUE TITLE
Sidebar is collapsed for first-time users

### ISSUE THREAD

**Issue by manjotsidhu** [CircuitVerse/Interactive-Book#582]
## Describe the bug

Any new user that comes to https://learn.circuitverse.org will see sidebar in collapsed state, the default behavior of sidebar should be shown to user unless manually collapsed.

## To Reproduce

1.  Go to 'https://learn.circuitverse.org' in Incognito Mode or InPrivate Window
2.  Sidebar will be collapsed.

## Expected behavior

First time user should see the sidebar in the first place.

**Comment by Palaksharma23** [comment]
i would like to work on this issue , can i take up this issue

**Comment by Palaksharma23** [comment]
i have solved the issue , will make a pr soon
