### ISSUE TITLE
Simulator Embeds overflow on mobile devices

### ISSUE THREAD

**Issue by manjotsidhu** [CircuitVerse/Interactive-Book#593]
## Describe the bug

Simulator embeds which are embedded in pages using iframe are overflowing on mobile devices.

## To Reproduce

1.  Go to 'https://learn.circuitverse.org/docs/seq-msi/mult-div.html'
3.  Scroll down to simulator embeds
4.  See error using chrome devTools responsive phone mode or physical mobile device.

## Expected behavior

The iframe should not overflow outside page width.

## Screenshots
![image](https://user-images.githubusercontent.com/22657113/144803687-9a577485-a0cf-4b38-8820-4057ceee3af8.png)

**Comment by Palaksharma23** [comment]
can you please assign me this issue @manjotsidhu
