### ISSUE TITLE
Documentation Improvements/Errors

### ISSUE THREAD

**Issue by DaKeiser** [CircuitVerse/Interactive-Book#6]
There are some documentation errors like 
- in [this](https://github.com/CircuitVerse/Interactive-Book/blob/master/docs/binary.md) there is incomplete sentence in line 67 of the code.
- Poor readability of text in Bitwise Operators subheading in [Operators in Binary](https://learn.circuitverse.org/docs/binary2.html). That was meant to be a table as far as I understand from the code.

There can be few improvements like
- Addition of XNOR gate [here](https://learn.circuitverse.org/docs/gates.html) as it is being used in [Interactive Gates](https://learn.circuitverse.org/docs/gatesi.html) chapter
- The general convention is XNOR, and NXOR is used sometimes. It would be easy for the students to understand if [it](https://github.com/CircuitVerse/Interactive-Book/blob/master/assets/images/XNOR_gate.png) was XNOR instead for NXOR.
- The [Two-Way Light Switch](https://learn.circuitverse.org/docs/gatesi.html) example can be implemented using CircuitVerse Simulator and it would be really helpful if CIrcuitVerse Simulator is used instead of the given example and keep the switch example as used [here](https://learn.circuitverse.org/docs/bool.html)

**Comment by Amansingla97** [comment]
gr8 you can start working on issues.

I have corrected the table in bitwise operator and there is no need in the two-way light switch as it is not giving any added advantage. Rest you can start working.

**Comment by SamriddhiMishra** [comment]
Can I correct the typo in line 67 of binary.md file?
