### ISSUE TITLE
Copyright is not changed to 2022

### ISSUE THREAD

**Issue by ZaidKhan2002** [CircuitVerse/Interactive-Book#606]
## Describe the bug
It's not bug, It's just on learn page at footer copyright year is 2021.

## To Reproduce

1.  Go to <a href="https://learn.circuitverse.org/">Learn</a>
2.  At bottom in footer Copyright year is not changed
3.  See error

## Expected behavior
 It should be 2022 I suppose.

## Screenshots
<img width="690" alt="Screenshot 2022-01-16 at 4 02 54 PM" src="https://user-images.githubusercontent.com/71960989/149710425-43279dac-ec56-4f90-940e-9cc1903fbdad.png">

## Desktop (please complete the following information):

* OS: iOS
* Browser: chrome
* Version: 12.0.1

## Smartphone (please complete the following information):

* Device: iPhoneX
* OS: iOS15
* Browser: safari
* Version: 15.1

## Additional context
It should be 2021 only or it should be 2022. Like on official mainpage and other pages it's 2022.

**Comment by manjotsidhu** [comment]
We have to update it to 2022.

**Comment by ZaidKhan2002** [comment]
Should I update it?
