### ISSUE TITLE
Buttons and Drop down not in accordance to Dark Mode

### ISSUE THREAD

**Issue by aayush-05** [CircuitVerse/Interactive-Book#61]
**Bug**
The buttons and the Drop down section on the "Interactive Karnaugh Map" page doesn't change with the Dark theme of the rest of the page.

**Screenshots**
![image](https://user-images.githubusercontent.com/47032027/68620802-425ace00-04f4-11ea-8443-54ae24a4b3a1.png)

**Solution**
Change the css files of the page to change the background to black.

**Comment by coding-CEO** [comment]
This issue is still not solved.
Can I work on this issue ?

**Comment by YashKumarVerma** [comment]
Sure @coding-CEO 
make sure you take references from https://github.com/CircuitVerse/Interactive-Book/pull/68

**Comment by coding-CEO** [comment]
> Sure @coding-CEO
> make sure you take references from #68

Sure.

**Comment by coding-CEO** [comment]
Solved this issue in #281 .
Please Review.

**Comment by coding-CEO** [comment]
@YashKumarVerma Close this issue.
This issue is resolved.
