### ISSUE TITLE
feat: Add transition effect to the Sidebar

### ISSUE THREAD

**Issue by adarrssh** [CircuitVerse/Interactive-Book#623]
## Is your feature request related to a problem? Please describe.
I would like to add some transition effects to the sidebar. The sidebar doesn't have any transition effect when it slides from left to right, it just pops out suddenly.

Current Sidebar sliding from left to right (without transition)

https://user-images.githubusercontent.com/85433137/176634686-457b4c09-7069-4b68-a8be-502fc11d5c0d.mp4

## Describe the solution you'd like
I would like to add transition effects to the sidebar ( watch the below video for transition reference only)

https://user-images.githubusercontent.com/85433137/176634772-069a0cd7-4f88-449c-adfe-eb26d8ba8ddc.mp4

Are you working on this? (Yes/No)
yes

**Comment by Rounak-28** [comment]
is this issue still open?

**Comment by diivi** [comment]
Please assign this to me

**Comment by Prerna-0202** [comment]
> Please assign this to me

Hey @diivi, Wait for a little, Once the core team approves the issue then you can start working on this issue.

cc @nitin10s @tachyons

**Comment by darshikaguptaa** [comment]
@nitin10s  @tachyons can you assign this issue to me?

**Comment by tachyons** [comment]
Thanks for the issue, but animation is not needed for sidebar
