### ISSUE TITLE
Update copyright year in about page 

### ISSUE THREAD

**Issue by Prerna-0202** [CircuitVerse/Interactive-Book#630]
## Describe the bug:-
The copyright year on the about page is still 2020.

## To Reproduce

1.  Go to 'https://learn.circuitverse.org/'
2.  Click on 'About'
3.  See the error

## Expected behavior
The year needs to be changed to the current year.

## Screenshots

![Screenshot (848)](https://user-images.githubusercontent.com/89515816/208904623-f79f1be8-6cbf-4490-930a-cf475b2b51f0.png)

## Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

**Comment by phershbe** [comment]
@prerna-0202 I can do this if you'd like another contributor. I'd like to contribute more things here, but I'll start super small. I know that this is a project from a university, so feel free to let me know if it's exclusive to the students there. Do you want `2022` as the date or `2023`?

**Comment by Prerna-0202** [comment]
> @Prerna-0202 I can do this if you'd like another contributor. I'd like to contribute more things here, but I'll start super small. I know that this is a project from a university, so feel free to let me know if it's exclusive to the students there. Do you want `2022` as the date or `2023`?

Hey @phershbe ,  Circuitverse is an open source project so anybody can contribute but looks like someone has already raise a pr for this issue, so you can checkout other good first issues and try to solve them.

**Comment by phershbe** [comment]
@Prerna-0202 Okay, thank you, I'll check out other issues here.

**Comment by Nitishupkr** [comment]
Can you assign me this issue

**Comment by nawarajshah** [comment]
i can work on this issue, can you assign to me?
