### ISSUE TITLE
Update Copyright Year at the Footer

### ISSUE THREAD

**Issue by Yasir761** [CircuitVerse/Interactive-Book#637]
## Describe the bug
In the footer copyright year is still 2022.
![Capture](https://user-images.githubusercontent.com/74600745/215332150-16027b58-219f-4857-be44-cbf764c1cc33.PNG)

## To Reproduce

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

## Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

## Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Comment by Malavi1** [comment]
Are you working on this?

**Comment by Yasir761** [comment]
@Malavi1 yes, Im working on this

**Comment by cherish2003** [comment]
is this issue still open can you please inform ??

**Comment by cherish2003** [comment]
i want to work on this issue
