### ISSUE TITLE
BUG: google logo should be more familiar one

### ISSUE THREAD

**Issue by harshsharma-11** [CircuitVerse/Interactive-Book#653]
## Describe the bug

the google social logo look not atttractive ,to improve user experience this should be replaced by more familiar google logo

## To Reproduce

1.  Go to 'any of topics below the home button'
2. Scroll down to bottom 
3.  you will see login options 
4.  google logo looks unfamiliar

## Expected behavior

instead more familiar google icon should be used 

## Screenshots

![Screenshot (206)](https://github.com/CircuitVerse/Interactive-Book/assets/138685168/917f756b-9e04-4c81-a83f-561e1f00d616)

logo to be used 

![Screenshot (207)](https://github.com/CircuitVerse/Interactive-Book/assets/138685168/3f2211b8-af99-4c86-9a69-09d0d62c43c3)

**Comment by harshsharma-11** [comment]
please review this issue @abstrekt

**Comment by tachyons** [comment]
This is from a third party provider and not configurable by us

**Comment by harshsharma-11** [comment]
okkk thanks for responding
