### ISSUE TITLE
Re-write content for boolean algebra

### ISSUE THREAD

**Issue by ShreyaPrasad1209** [CircuitVerse/Interactive-Book#66]
**Problem**
https://learn.circuitverse.org/docs/bool.html appears to be plagiarized from https://www.tutorialspoint.com/computer_logical_organization/boolean_algebra.htm.

**Solution**
Re-write the content in your own words.

**Are you working on this task?**
No, for GCI participants under medium, documentation labels.

**Comment by aayush-05** [comment]
According to me, almost 70% of the content on the website is copied from TutorialsPoint.
We can have a team of say 3-4 people having an electronics background to rewrite the whole content again.
Solely relying on students under gci won't be a good option, because it would make different pages mismatched due to different styles of writing.
What do you think @tachyons ?

**Comment by ShreyaPrasad1209** [comment]
That's why I'm not making them re write the whole book. I'm giving them only those sections which can be done by pre university students as well. I believe boolean algebra can be understood by them.

**Comment by aayush-05** [comment]
Sure @ShreyaPrasad1209 
I was just saying that you can mention a template so as to keep the content style on different pages uniform and similar.
Like if the content has to written in the third person or not, if the circuit diagrams has to made on circuitverse simulator or images would be fine, etc.
May be we can mention the details on the gci dashboard itself.

**Comment by tachyons** [comment]
Boolean algebra contents will be hard for school students, As far I know only computer science higher secondary students have Boolean algebra in their syllabus

**Comment by tachyons** [comment]
It is better to be written by someone have background in boolean algebra and electronics, few people already volunteered to do that

**Comment by abhinavsri360** [comment]
I am on this
