### ISSUE TITLE
Error while running the "bundle exec jekyll serve"

### ISSUE THREAD

**Issue by Musharraffaijaz** [CircuitVerse/Interactive-Book#661]
## Error
While running the code "bundle exec jekyll serve" the editor is not able to serve the application, there are couple of issues with this as:
The error message indicates that the exists? method is not found for the File class. This is because the correct method name is exist?, not exists?.

The error is coming from the jekyll-scholar gem, specifically in the utilities.rb file.

Here's the problematic line:

This line should be corrected to:

However, as this is a third-party gem, you can't directly modify it. You should report this issue to the maintainers of the jekyll-scholar gem.

## Screenshots

![image](https://github.com/CircuitVerse/Interactive-Book/assets/49266438/85fad6ee-6e9d-4bfc-980c-2b189268d668)
![image](https://github.com/CircuitVerse/Interactive-Book/assets/49266438/5013ac2a-288d-452a-8446-45d216f5bd36)

## Desktop:

* OS Windows 10
* ruby -v 3.2.2
* Bundler -version: 2.2.19
* Gem Version: 3.4.10

**Comment by tachyons** [comment]
This should be fixed by now
