### ISSUE TITLE
Copyright year is outdated it shoud be updated from `2023` to `2024`

### ISSUE THREAD

**Issue by Pradipram** [CircuitVerse/Interactive-Book#670]
## Describe the bug

In footer section the year shown is `2023` but it should be `2024`

## To Reproduce

1.  Go to `https://learn.circuitverse.org/`
3.  Scroll down to `footer section`
4.  there you will get this error

**Comment by subhamkumarr** [comment]
I am working on this issue.

**Comment by subhamkumarr** [comment]
I have raised PR https://github.com/CircuitVerse/Interactive-Book/pull/671
