### ISSUE TITLE
Unnecessary repetition of the paragraph

### ISSUE THREAD

**Issue by subhamkumarr** [CircuitVerse/Interactive-Book#679]
## Describe the bug
There is an unnecessary repetition of the paragraph.

## Screenshort

**Comment by subhamkumarr** [comment]
@tanmoysrt Could you please review this PR

**Comment by subhamkumarr** [comment]
@tachyons  @tanmoysrt I have raised [PR](https://github.com/CircuitVerse/Interactive-Book/pull/680) for this, could you please review.

**Comment by tachyons** [comment]
This issue is invalid, see https://github.com/CircuitVerse/Interactive-Book/pull/680#issuecomment-1935541043
