### ISSUE TITLE
Table flowing outside of the page

### ISSUE THREAD

**Issue by aayush-05** [CircuitVerse/Interactive-Book#71]
The table generated on the "FLIPFLOP Interaction" page flows outside of the screen. This makes the output column not visible on the website. Since there is no horizontal scrollbar, there isn't any way possible to see the last column of the table.

**Screenshots**
![image](https://user-images.githubusercontent.com/47032027/68832502-1ea3ad80-06d7-11ea-999c-a2f128a57c52.png)
_(The Z column after the DB column isn't visible)_
**Solution**
Either make the table responsive to shift its size according to the browser window or add a horizontal navbar to be able to scroll to the last column.

**Comment by coding-CEO** [comment]
I solved this problem in PR #264 
Please Review.
