### ISSUE TITLE
Add bootstrap to Buttons

### ISSUE THREAD

**Issue by sakshi1499** [CircuitVerse/Interactive-Book#74]
Bootstrap missing in buttons.
![stg](https://user-images.githubusercontent.com/42520146/68854714-a8b53b80-0702-11ea-8223-52ccc0ed9352.PNG)

**Comment by aayush-05** [comment]
Hey @sakshi1499 
I don't think we are using any bootstrap in Interactive-Book; the styling mainly consists of sass and jekyll.
But yes we can add additional styling to improve their look.

**Comment by sakshi1499** [comment]
@aayush-05 I was referring this to create consistent buttons throughout the book. Look at these buttons, they can be added instead of the normal button. What do you think?
![buttons](https://user-images.githubusercontent.com/42520146/68857835-b9b57b00-0709-11ea-8497-3b1f27944933.PNG)

**Comment by aayush-05** [comment]
Sure, a more uniform look to the whole website would be great.
I made a pull request for the same. You can check #77

**Comment by aayush-05** [comment]
@tachyons @nitin10s this can be closed, PR already merged

**Comment by nitin10s** [comment]
Fixed in #77
