### ISSUE TITLE
Left Margin should be reduced

### ISSUE THREAD

**Issue by sakshi1499** [CircuitVerse/Interactive-Book#76]
The left margin is too wide which ultimately reduces space for the actual documentation.
![lm](https://user-images.githubusercontent.com/42520146/68857459-d3a28e00-0708-11ea-8059-27f264d7505d.PNG)

**Comment by udbhav-s** [comment]
Hi, is this issue open to fix? I saw this as a GCI task and I can try working on it.

**Comment by sakshi1499** [comment]
@udbhav-s I think @aayush-05 has already made a PR for the same. Ask the mentor for this issue, if you can work on it or not.

**Comment by udbhav-s** [comment]
Yeah, I messaged him and he said I can work on it. I checked the website and the sidebar width was still the same despite the PR so I made a separate pull request: 
https://github.com/CircuitVerse/Interactive-Book/pull/102

**Comment by sakshi1499** [comment]
@udbhav-s Actually that PR hasn't been merged that is why you can't see the changes. But do as your mentor directed. :)

**Comment by aayush-05** [comment]
@tachyons @nitin10s this can be fixed, PR already merged

**Comment by coding-CEO** [comment]
@YashKumarVerma This Issue can be closed.
