### ISSUE TITLE
Setup Gitpod for this project

### ISSUE THREAD

**Issue by tachyons** [CircuitVerse/Interactive-Book#78]
Gitpod helps to make development and reviewing PRs easier by proving cloud IDE. Having Gitpod setup for this repo will be great

**Comment by sal2701** [comment]
Hey, can I take up this issue?

**Comment by tachyons** [comment]
Sure

**Comment by sakshi1499** [comment]
@sal2701 You can ask me, if you need some help, I have developed Interactive Book in my gitpod :)

**Comment by sakshi1499** [comment]
Is someone working on this or should I? @tachyons

**Comment by sal2701** [comment]
I wanted to work on this but someone already sent a PR.

**Comment by sakshi1499** [comment]
I don't think it was right. .yml file wasn't fine I think. But someone is working on it. You can look for some other issue. Ask me if you need any help 😊 @sal2701

**Comment by fluctix** [comment]
Can I work on this issue?

**Comment by tachyons** [comment]
Sure

**Comment by fluctix** [comment]
So I had made the gitpod.yml file.and gitpod dockerfile but it turns out while serving it due to a Jekyll configuration , it obtains the css files , images etc (which have absolute paths) over http so there is a mixed content error and as a result there is no styling in the website.
@sakshi1499 @tachyons can you please help me with this?

**Comment by pranavmodx** [comment]
@thiefie Are you still working on it? If not, I can take it up.

**Comment by YashKumarVerma** [comment]
@pranavmodx @criticic @sakshi1499 
Is anyone of you working on this issue / would like to work on it ?

**Comment by nisarhassan12** [comment]
> So I had made the gitpod.yml file.and gitpod dockerfile but it turns out while serving it due to a Jekyll configuration , it obtains the css files , images etc (which have absolute paths) over http so there is a mixed content error and as a result there is no styling in the website.
@sakshi1499 @tachyons can you please help me with this?
>
> As a side note , I use chrome

Hi! all Let me know if the above is still relevant.

**Comment by YashKumarVerma** [comment]
quick reference, by the time this is not merged, y'all can use this chrome extension, it's good btw.

https://chrome.google.com/webstore/detail/gitpod-online-ide/dodmmooeoklaejobgleioelladacbeki

p.s., this is neither my extension nor have I contributed to it's contents.

**Comment by nisarhassan12** [comment]
> quick reference, by the time this is not merged, y'all can use this chrome extension, it's good btw.

@YashKumarVerma Thanks. Sorry I hope you already know that the extension would only add an "Open in Gitpod" button that helps start a workspace on every GitHub repo. Without the [config](https://www.gitpod.io/docs/config-gitpod-file/) `.gitpod.yml` Gitpod would do nothing other than cloning the repo.

While Gitpod can do a whole bunch of cool stuff that'll help contributors and maintainers greatly.

For instance, try this https://gitpod.io/#https://github.com/mobxjs/mobx/

You'll find out that Gitpod will not only clone the repo but also:

- install all the dependencies.
- run the build task.
- start the docs server.
- run tests in watch mode.
- run the performance benchmarks.

and with pre-builds enabled it installs the dependencies and run the build task ahead of time.

This is how it looks:

![image](https://user-images.githubusercontent.com/46004116/82118397-a0f95100-9790-11ea-829c-8b05b8444a03.png)

Should I go ahead and make a PR for the brief Gitpod setup Thanks.

**Comment by YashKumarVerma** [comment]
> > quick reference, by the time this is not merged, y'all can use this chrome extension, it's good btw.
> 
> @YashKumarVerma Thanks. Sorry I hope you already know that the extension would only add an "Open in Gitpod" button that helps start a workspace on every GitHub repo. Without the [config](https://www.gitpod.io/docs/config-gitpod-file/) `.gitpod.yml` Gitpod would do nothing other than cloning the repo.
> 
> While Gitpod can do a whole bunch of cool stuff that'll help contributors and maintainers greatly.
> 
> For instance, try this https://gitpod.io/#https://github.com/mobxjs/mobx/
> 
> You'll find out that Gitpod will not only clone the repo but also:
> 
> * install all the dependencies.
> * run the build task.
> * start the docs server.
> * run tests in watch mode.
> * run the performance benchmarks.
> 
> and with pre-builds enabled it installs the dependencies and run the build task ahead of time.
> 
> This is how it looks:
> 
> ![image](https://user-images.githubusercontent.com/46004116/82118397-a0f95100-9790-11ea-829c-8b05b8444a03.png)
> 
> Should I go ahead and make a PR for the brief Gitpod setup Thanks?

Thank you for giving a detailed reply to the thread, this would be really helpful for those who needed more info on the context.


P.S. : the extension can never replace the original gitpod config, it's to only give you a fast network box to work on
![image](https://user-images.githubusercontent.com/14032427/82119186-14ec2700-979a-11ea-9e6d-e55757eebd97.png)

**Comment by tachyons** [comment]
@nisarhassan12 We already have such setup for circuitverse main repo

**Comment by nisarhassan12** [comment]
Thanks! @tachyons @YashKumarVerma I have started working on it the setup is done but in the preview there is no styling. Once that's fixed I'll make a PR.

**Comment by eKuG** [comment]
Somebody working on this issue?

**Comment by nisarhassan12** [comment]
@eKuG Thanks! I have added the gitpod config https://github.com/nisarhassan12/Interactive-Book/blob/master/.gitpod.yml but in the workspace preview, there seem to be no styles showing up. Once I'm able to fix that I'll make a Pr for sure. The issue is that `localhost:4000` is hardcoded while Gitpod expects the URL to be something like https://4000-${workspace-url}.gitpod.io.

![image](https://user-images.githubusercontent.com/46004116/82823522-2bdcf880-9ec1-11ea-9f15-7452b6a2cf44.png)

You can reproduce this via opening a workspace via the following link.

https://gitpod.io/#https://github.com/nisarhassan12/Interactive-Book/

**Comment by manjotsidhu** [comment]
Fixed by #460
