### ISSUE TITLE
Change Mouse pointer when hovered on gates

### ISSUE THREAD

**Issue by Amansingla97** [CircuitVerse/Interactive-Book#8]
Currently, the mouse pointer does not change it's state from an arrow to hand when hovered over a gate in interactive gates module
![Screen Recording 2019-07-17 at 8 53 09 pm](https://user-images.githubusercontent.com/20012612/61388396-7a029200-a8d5-11e9-8775-3aace2efccb9.gif)

**Comment by aayush-05** [comment]
@tachyons @nitin10s this can be closed, PR merged

**Comment by nitin10s** [comment]
Closed via #18
