### ISSUE TITLE
Edit contents and Dark Mode should be buttons and not link inside buttons list.

### ISSUE THREAD

**Issue by shubhankarsharma00** [CircuitVerse/Interactive-Book#88]
![image](https://user-images.githubusercontent.com/32474302/69037384-ce498a00-0a0d-11ea-8f5f-140f8eddac5e.png)
 These acts as a link inside a button and you have to click on the text to trigger the redirect. I think the link should be btn class and not the list item.

**Comment by shubhankarsharma00** [comment]
To be clearer I think this:
https://github.com/CircuitVerse/Interactive-Book/blob/7ca082cfb8c08be002332443feb760a948ffd328/_layouts/default.html#L32-L33
Should be:
 ```<li class="d-inline-block my-0{% unless forloop.last %} mr-2{% endunless %} js-toggle-dark-mode"><a class = "btn">Dark Mode</a></li>```
```<li class="d-inline-block my-0{% unless forloop.last %} mr-2{% endunless %} "><a class = "btn" href="{{ site.github.repository_url }}/tree/master/{{ page.path }}">Edit on Github</a></li>```

**Comment by aayush-05** [comment]
Hey !
I don't think that the given solution would work as expected.
It gives the following output :

![image](https://user-images.githubusercontent.com/47032027/69568121-04c06f80-0fe1-11ea-990a-9fa752fed765.png)

Also, when the btn class is applied to list element, it gets automatically applied to the anchor element since it is a child element of list.

**Comment by coding-CEO** [comment]
This is not an issue in current repo.
@YashKumarVerma @Shivansh2407 This issue can be closed.

**Comment by YashKumarVerma** [comment]
> This is not an issue in current repo.
> @YashKumarVerma @Shivansh2407 This issue can be closed.

how exactly ?

**Comment by Shivansh2407** [comment]
> This is not an issue in current repo.
> @YashKumarVerma @Shivansh2407 This issue can be closed.

The Dark Mode Button work when we click on them without clicking on the text, But the Edit on github is still not working the way it is needed .

**Comment by manjotsidhu** [comment]
Fixed by #460
