### ISSUE TITLE
The cap condition on number not properly implemented in "operation in Binary" section and calculate button should be repositioned.

### ISSUE THREAD

**Issue by ankit1414** [CircuitVerse/Interactive-Book#89]
the range for numbers is 0 to 255 for the AND operation visulaizer... it currently displays notification about this constraint but inserts the new digit.<br/>
![operators in binary](https://user-images.githubusercontent.com/45892437/69244703-6b9ded00-0bcb-11ea-8635-6ab25b89e19d.png)
it should not add  the new digit after showing the notification popup.<br/>
and maybe the calculate button should be repositioned after the second number.

**Comment by coding-CEO** [comment]
This issue is fixed in #319 .
