### ISSUE TITLE
Fix typos in the whole book

### ISSUE THREAD

**Issue by sal2701** [CircuitVerse/Interactive-Book#92]
There are a few typos in the Interactive-Book and fixing them is necessary and requires one to go through the whole book

**To Do**
* Go through the Interactive-Book and find typos in the text and fix them.

**Are you working on it?**
Nope. For GCI 2019

**Comment by harshitaaaaaa** [comment]
Can I work on this?

**Comment by YashKumarVerma** [comment]
A lot of content is being re-written. Please check GSoD2020 Branch.

**Comment by harshitaaaaaa** [comment]
> A lot of content is being re-written. Please check GSoD2020 Branch.

Okay I'm checking it out! Thankyou

**Comment by sal2701** [comment]
Closing issue as not applicable anymore
