### ISSUE TITLE
List overflowing in "Binary Flags" activity

### ISSUE THREAD

**Issue by sal2701** [CircuitVerse/Interactive-Book#93]
**Problem faced**
While doing the [Binary Flag](https://learn.circuitverse.org/docs/application2.html#binary-flags) activity, the list of subjects overflows and overlaps with the text below.

**Solution**
* Create a larger box/dynamically sized box to fit the complete list properly

**Related Photos**
![Screenshot from 2019-11-29 04-01-42](https://user-images.githubusercontent.com/42511766/69834170-c59f5200-125e-11ea-9d6b-525cf097afdc.png)

**Are you working on it?**
Nope. For GCI 2019

**Comment by pranavmodx** [comment]
Please close the issue if it's solved.
