### ISSUE TITLE
Press R to reload Flip-Flop Table Generator

### ISSUE THREAD

**Issue by sal2701** [CircuitVerse/Interactive-Book#95]
#### I am submitting a -
* **Feature Request**

#### Describe your bug/feature -
Right now, we have to press "F" to start the [State Table Generator](https://learn.circuitverse.org/docs/flipflop2.html). Once we a table is generated we have to reload/click the link to start the process again.

#### Current behaviour -
No button to restart the State Table Generator.

#### Expected behaviour -
Press "R" to restart the State Table Generator. Can be further improved to use "N" to proceed to next step instead of clicking Next button.

#### Are you working on this issue? (Yes/No)
Nope. For GCI 2019

**Comment by mohit-003** [comment]
Can I work on this? When will this be a task?

**Comment by sal2701** [comment]
Hey @mohit-003, we'll add this as a task soon, we need to fix something else before making this as a task. Will add #111 as a task so you can work on this after that is fixed.

**Comment by mohit-003** [comment]
I completed this 😁 I'll make a PR when you say @sal2701 .

**Comment by sal2701** [comment]
@mohit-003 Cool! I've added the task check it out.
[Task](https://codein.withgoogle.com/dashboard/tasks/6368232177401856/)

**Comment by mohit-003** [comment]
Can I make a PR now and take the task later? because I have already taken another task.

**Comment by sal2701** [comment]
You can do it but claim it before someone else does. I can't stop someone else from claiming the task. If someone claims it before you I will have to consider their contributions before you, this is what GCI demands I really can't do much in this regard :slightly_smiling_face:
