### ISSUE TITLE
Overflowing Binary numbers

### ISSUE THREAD

**Issue by Shweta0002** [CircuitVerse/Interactive-Book#97]
The binary numbers are overflowing from the boxes .
Steps to reporduce:
Go to the link below
https://learn.circuitverse.org/docs/binary.html

![Screenshot from 2019-12-01 20-14-50](https://user-images.githubusercontent.com/40588060/69915673-b810e480-1477-11ea-9990-f1ca6c73ef46.png)

Expected Behaviour: 
The numbers should fit the box, rather than overflowing .

**Comment by Parikshit-Hooda** [comment]
@Shweta0002 
![Capture](https://user-images.githubusercontent.com/25405707/70289464-d6217080-17fa-11ea-9bc5-17bd026da591.PNG)
